### ISSUE TITLE
Small styling issue with horizontal overflow

### ISSUE THREAD

**Issue by mikedotexe** [near/near-explorer#1001]
I saw this today and thought I'd flag a minor UI / styling issue.

![explorer-issue](https://user-images.githubusercontent.com/1042667/169364313-27de90f7-e9b8-4893-8ebd-7a0f00000c0c.gif)

❤️

**Comment by luixo** [comment]
Thanks for pointing out!
Fix is on the way: https://github.com/near/near-explorer/pull/1016
