### ISSUE TITLE
Error when trying to build frontend Dockerfile

### ISSUE THREAD

**Issue by leoporoli** [near/near-explorer#1023]
## Story

I want to build the Docker image for the frontend project, so in order to build it I'm doing the following steps:

First, I added this line in the Dockerfile, because it is needed

<img width="339" alt="image" src="https://user-images.githubusercontent.com/29951623/171282404-983efc36-008e-495b-ad92-652db6a1f57a.png">

Then, I try to build the frontend image with this command in the root: 
` docker build -t kurtosistech/near-explorer_frontend:8df44b7 -f ./frontend/Dockerfile ./`

And it throws this error:

` 
[+] Building 105.5s (19/25)                                                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 1.02kB                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 34B                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/mhart/alpine-node:16                                                                                                        1.2s
 => [internal] load build context                                                                                                                                      0.0s
 => => transferring context: 22.39kB                                                                                                                                   0.0s
 => [stage-1 1/7] FROM docker.io/mhart/alpine-node:16@sha256:c9014e9e5b33f29d47c867ea548edc0235ba71677f40456409a44c278d8a8e01                                          0.0s
 => CACHED [stage-1 2/7] WORKDIR /near-explorer/frontend                                                                                                               0.0s
 => CACHED [build  2/15] WORKDIR /near-explorer/common                                                                                                                 0.0s
 => CACHED [build  3/15] COPY ./common/package.json ./common/package-lock.json ./                                                                                      0.0s
 => CACHED [build  4/15] RUN npm clean-install                                                                                                                         0.0s
 => CACHED [build  5/15] WORKDIR /near-explorer/frontend                                                                                                               0.0s
 => CACHED [build  6/15] COPY ./frontend/package.json ./frontend/package-lock.json  ./                                                                                 0.0s
 => CACHED [build  7/15] RUN npm clean-install --prod                                                                                                                  0.0s
 => CACHED [build  8/15] RUN cp -a node_modules ../production_node_modules                                                                                             0.0s
 => CACHED [build  9/15] RUN npm clean-install                                                                                                                         0.0s
 => CACHED [build 10/15] COPY ./common ../common                                                                                                                       0.0s
 => CACHED [build 11/15] COPY ./frontend ./                                                                                                                            0.0s
 => CACHED [build 12/15] COPY ./tsconfig.json ../                                                                                                                      0.0s
 => [build 13/15] RUN cp -a ./node_modules ../production_node_modules                                                                                                 61.4s
 => ERROR [build 14/15] RUN npm run build                                                                                                                             42.5s
------
 > [build 14/15] RUN npm run build:
#19 2.750 
#19 2.750 > near-explorer-frontend@0.0.1 build
#19 2.750 > next build
#19 2.750 
#19 14.11 warn  - You have enabled experimental feature(s).
#19 14.11 warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
#19 14.11 
#19 14.48 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#19 14.48 This information is used to shape Next.js' roadmap and prioritize features.
#19 14.48 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#19 14.48 https://nextjs.org/telemetry
#19 14.48 
#19 15.11 info  - Checking validity of types...
#19 42.35 Failed to compile.
#19 42.35 
#19 42.35 ./jest.setup.ts:1:1
#19 42.35 Type error: Cannot find name 'jest'.
#19 42.35 
#19 42.35 > 1 | jest.useFakeTimers().setSystemTime(new Date(2019, 1, 1));
#19 42.35     | ^
#19 42.35   2 | export {};
#19 42.35   3 | 
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
`

## Acceptance Criteria

- [ ] AC1
- [ ] AC2
- [ ] Mobile ok
- [ ] Tested

## Assets

- Mockup: 

## NOTES

-

**Comment by luixo** [comment]
Thanks for reporting!
Just discovered this today as well, it seems to be broken after the [workspaces commit](https://github.com/near/near-explorer/commit/ef481ea701fc0f1b3425f02a943dadd6a6b0a7d5).
I'll make a PR to fix this soon.

If you need to run an explorer - you can do that without a docker in a few steps:
1. npm install
2. docker-compose build wamp && docker-compose up wamp
3. npm run -w backend dev:mainnet
4. npm run -w frontend dev:local-wamp

And soon (after [TRPC PR](https://github.com/near/near-explorer/pull/1008) is merged) step 2 will be skipped.

**Comment by mieubrisse** [comment]
Hey @luixo , unfortunately we actually need Docker images for the Kurtosis NEAR localnet, since the existing local dev setup is predicated on having containers. Folks looking to do localnet dev are currently blocked due to the latest NEAR CLI (4.0 I believe) being incompatible with the older version that was inside of Kurtosis, so we're trying to push new images ASAP. Any idea when we'd be able to get new containers so we can unblock local dev users?

**Comment by luixo** [comment]
Can you use an image of the version before [workspaces commit](https://github.com/near/near-explorer/commit/ef481ea701fc0f1b3425f02a943dadd6a6b0a7d5) before I fix it?
I'll do this task top priority anyway, but it might take some time.

**Comment by mieubrisse** [comment]
Thanks @luixo !!
