### ISSUE TITLE
near explorer setup issue

### ISSUE THREAD

**Issue by TanyaSrivastava-Dipali** [near/near-explorer#1054]
I am trying to setup explorer for my near indexer database.I have set environment variables with 3 different databases.Still getting this error
WAMP setup: connecting to ws://wamp:8080/ws with ticket THIS_IS_LOCALHOST_SECRET
backend_1   | Retrying HTTP request for https://127.0.0.1:3030/ because of error: FetchError: request to https://127.0.0.1:3030/ failed, reason: connect ECONNREFUSED 127.0.0.1:3030.

kindly tell how to setup env for near localnet indexer.

**Comment by frol** [comment]
@TanyaSrivastava-Dipali it seems you are not using the latest master version since we already migrated away from WAMP to TRPC. Please, pull the latest master version and try again (I recommend you drop node_modules along your way to have a clean install)

**Comment by luixo** [comment]
I'll close the issue.

@TanyaSrivastava-Dipali 
Please feel free to file a new one if you have a problem.
