### ISSUE TITLE
Search by block hash does not find the block

### ISSUE THREAD

**Issue by frol** [near/near-explorer#1081]
Take any block hash, e.g. `4usxPdL68XbQXBeZPGj56wH1FAqrXhuFygHTz27xodMU`, and try to search it on Explorer. Even though I can perfectly open the page https://explorer.near.org/blocks/4usxPdL68XbQXBeZPGj56wH1FAqrXhuFygHTz27xodMU, the search still says that there is nothing found.

@shelegdmitriy Could you take a quick look at it?

**Comment by shelegdmitriy** [comment]
@frol checkout the linked PR above
