### ISSUE TITLE
Nodes online are not displaying and Regular staking pool metadata check crashed

### ISSUE THREAD

**Issue by bimmerv** [near/near-explorer#1100]
Hi.
I have configured:
near-indexer-for-explorer
near-contract-helper
near-wallet
near-explorer
for local development in localnet (all this stuff located on my web-server, for development purposes).
Ubuntu 20, GCP instance.
And now I have 2 errors.
1. When I run docker-compose I receiving the next errors:
```
near-explorer-backend-1   | Regular staking pool metadata check crashed due to: Error: [-32000] Server error: account name.near does not exist while viewing
``` 
There are no more other errors expect that (And it repeat every second)

2. In near-explorer I don't see Nodes online. This field says "Temporary unavailable".
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/36265578/192858907-955a2341-bbbd-4598-9542-ab2d26de9532.png">

Can you help me with them? Thanks

**Comment by frol** [comment]
Your node should report telemetry to `http://<localnet-explorer>/api/nodes` (check your `.near/config.json`)

**Comment by bimmerv** [comment]
@frol thanks. the second issue was resolved.
And what about first?

**Comment by frol** [comment]
@bimmerv name.near is a validators registry on mainnet, which obviously does not exist on localnet, it should not cause any problems, just ignore it
