### ISSUE TITLE
Explorer does confusing eager validation on account searches

### ISSUE THREAD

**Issue by flmel** [near/near-explorer#1119]
I search for an account that has been deleted. eg. `token2.dev-1669896650363-61678876374957`
The search says the account does not exist and stops the query being made.
If I go on and put the account as a parameter in the browser nav (skipping the eager validation) for eg.
`https://explorer.testnet.near.org/accounts/token2.dev-1669896650363-61678876374957`

It shows me that the account has existed but has been deleted. I understand that's probably one way to reduce queries but I find the behaviour confusing maybe the message that  "does not exist" shall be changed

**Comment by luixo** [comment]
Can you please specify where do you look it up?
I opened `explorer.testnet.near.org`, put a `token2.dev-1669896650363-61678876374957` in the search box, hit enter and got redirected to the account page in a couple of seconds.

**Comment by flmel** [comment]
That's very odd . I'm sure it wasn't browser or connection issue at the time however can't reproduce it myself at the moment.
