### ISSUE TITLE
Search via Receipt ID doesn't work

### ISSUE THREAD

**Issue by pustovalov** [near/near-explorer#1141]
Hi,

NEAR explorer says that you can search by `Search for Account ID, Receipt ID, Txn hash, Block hash, or Block height`

This transaction
https://explorer.near.org/transactions/AAPtmqFMRK3gxeNrKNVEfRpJ6UzS3rW4qvUUy1ZDmzdR

has this receipt id: `Gs8phoC6vYGUuDNSZJ714rseLKbAni4orm7VNJYjPBWM`

when I try to find transaction by receipt id, NEAR explorer can’t find it
![NEAR Explorer | Dashboard 2023-01-17 12-25-02](https://user-images.githubusercontent.com/1568885/212887129-bafb2a6e-0df7-4b69-b20c-af8509360fb9.jpg)

**Comment by luixo** [comment]
Thanks for pointing out!
The frontend didn't roll out properly and tried to fetch data from removed endpoints.
It's been fixed.
