### ISSUE TITLE
Broken link to NEAR wiki on homepage of https://explorer.near.org/

### ISSUE THREAD

**Issue by saketh-are** [near/near-explorer#1186]
The explorer homepage has a section "Node validating" whose tooltip links
https://wiki.near.org/resources/faq/integrator-faq#validators

The link is dead and leads to a Page Not Found.

**Comment by luixo** [comment]
@frol 
What was the original intent of the link? It says "docs" though I'm not sure there were docs in there.
I suggest we use either [a very general page](https://near.org/about/network/validators/) on validators or [staking and delegation](https://near-nodes.io/validator/staking-and-delegation).

**Comment by luixo** [comment]
[Merged](https://github.com/near/near-explorer/commit/9c1f543c2e930886c9b07e13c0ffccf062ea5833)
