### ISSUE TITLE
Chart for amount of gas spent over time

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#122]
Also interesting in normalization gas over number of transaction.
E.g. track how "complex" transactions are becoming.

**Comment by frol** [comment]
1. Should the chart be cumulative?
2. Normalized for what period of time?

**Comment by ilblackdragon** [comment]
1. On dashboard a cumulative would be good. In page with gas details can have also per day aggregation.
2. Normalization - per day probably is good

**Comment by frol** [comment]
Closing in favor of #189 and #350.
