### ISSUE TITLE
CGNEARkXDOO8ZvlRw

### ISSUE THREAD

**Issue by Mido251188** [near/near-explorer#1226]
## Story

As a USER who PRECONDITIONS, I want to DO_THING so I can ACCOMPLISH_GOAL.

## Acceptance Criteria

- [ ] AC1
- [ ] AC2
- [ ] Mobile ok
- [ ] Tested

## Assets

- Mockup: 

## NOTES

-

**Comment by shelegdmitriy** [comment]
Please add more info on what's the problem and reopen the issue.
