### ISSUE TITLE
Show last finalize block/height

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#127]
Now in the header there is a `last_quorum_pre_commit`, which is the hash of the last finalized block. Using this information from the latest block, we can show latest height of the final block.

For example: https://bloks.io/ under last block there is height of "Last Irreversible Block". And when you click on the block, you see if it's Irreversible or pending.

Additionally, we can show if blocks are final or not (this needs extra changes in RPC).

**Comment by frol** [comment]
Design or sketch is needed for this one.

**Comment by frol** [comment]
Now, we have DoomSlug finality on staging, so we need to also indicate that as well.

@ilblackdragon Should we indicate this only on the block details page or should we also display those on the Dashboard somehow? (I would imagine some small indicator, e.g. color dot with a tooltip on hover or something like that, next to every block on the right column of latest blocks)

Just for the reference, here is the screenshot of how it is displayed on blocks.io:

![image](https://user-images.githubusercontent.com/304265/74891825-b6640800-5366-11ea-892f-870a94fb25b9.png)

Implementation-wise, we need to fetch the information for the latest block height on the frontend (implement a proxy-call for `block` RPC on the backend like [we have for `tx` RPC call](https://github.com/nearprotocol/near-explorer/blob/685eaa3e52016025519ede72a421d84ab37a589a/backend/src/wamp.js#L60-L62)), and use `last_ds_final_block` (near-final [DoomSlug]) and `last_quorum_pre_commit` (final [NFG]) to do two other blocks calls to fetch the block heights of the respective blocks, and then we display "Pending Finalization", "NEAR Finalized" (when the block height is `<= last_ds_final_block`), or "Finalized" (when the block height is `<= last_quorum_pre_commit`).

NOTE: `last_ds_final_block` is greater or equal (I don't think equality is possible, but this does not really matter in this context) than `last_quorum_pre_commit`, which means that when the block height is `<= last_quorum_pre_commit`, we should display "Finalized" ("NEAR Finalized" is a slightly weaker finalization state).

@ilblackdragon Is `last_quorum_pre_vote` useful for us here?

**Comment by bowenwang1996** [comment]
`last_quorum_pre_vote` isn't useful in this context

**Comment by icerove** [comment]
we already have this final block data but not showing directly but as isFinal tag
