### ISSUE TITLE
Search on dashboard does not work for non-synced transactions

### ISSUE THREAD

**Issue by frol** [near/near-explorer#153]
## Story

As a user who is interested in the transactions that just happened, I want to enter the transaction hash into a search box and get to the transaction details page even if it is not synced yet. (the page is expected to work just fine in this case, but it seems that search does not "see" new transactions via the API calls it does; search should just query nearcore via explorer-wamp `nearcore-tx` RPC)

## Acceptance Criteria

- [ ] Search by a hash of a very recent transaction (which is already available via nearcore RPC) leads to Transaction Details page
- [ ] Tested

**Comment by icerove** [comment]
Unfortunately, I touch this a little bit, it raised some questions:
1. for nearcore-tx method, transaction hash and signer id are both required and only transaction hash could not fetch correctly.
2. in transaction status method, there will be no block hash included and can not get gas price, with also not getting trnsactionFee. 
Do we still want this implementation? If so, I recommend having a separate search for this one and some part of the transactionDetails page need fix. @frol

**Comment by bowenwang1996** [comment]
In the single shard case we can hack around the transaction id by prepending an arbitrary string, although I think it makes sense to resolve it properly, i.e, asking user to enter `<accountId>:<transactionHash>`

**Comment by frol** [comment]
I suggest we change our requirements so signer (sender) account ID is required along with the transaction hash. We are in control of all the links we provide to transactions (near-api-js, near-shell, Explorer itself), so we should be able to update our code so that we have the account ID in the URL itself, and thus the frontend will be able to use nearcore-tx method.
