### ISSUE TITLE
Deleted account is not shown in the explorer at all

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#193]
Steps to reproduce:
Create account & delete account:
```
near create_account testtest --masterAccount someaccount
near delete_account testtest someaccount
```

Check in explorer that `testest` is not found.
Re-create account back and see that transaction history from before is shown.

**Comment by frol** [comment]
@ilblackdragon We had this conversation before... Do you believe we should not display the old transactions? It is unclear how to maintain that (e.g. what if I open a list of transactions made to some other recipient/contract, should we hide the transactions made by a deleted user?

There is no special case for account deletion action, so I don’t know why you could not see the account after you deleted it. We need to reproduce that @icecove

**Comment by ilblackdragon** [comment]
We should show transactions for deleted account. This bug is about not seeing deleted account (not that when I re-create it's still there).

**Comment by icerove** [comment]
I reproduce the issue and after I  re-create the account, the transactions would have the old deleted action and new create transaction.

**Comment by icerove** [comment]
will fix this

**Comment by ilblackdragon** [comment]
@icerove The bug is *not* that you can see old transaction.
The bug is that you can not see deleted account.

**Comment by icerove** [comment]
I got that, not explaining right.

**Comment by icerove** [comment]
I think it is somehow the issue for near-shell. explorer just show what content from transactions and do not do any transform when account is deleted.

**Comment by icerove** [comment]
@ilblackdragon  what is it supposed to show for the deleted accounts? just like normal one in the account list or another page? and on the detail page, what do you want to show?

**Comment by ilblackdragon** [comment]
We should show log of transactions for this account and the details about account that are available (for example there is no balance / stake anymore to show) and mark that this account is deleted in UI in some way.
