### ISSUE TITLE
Incorrect TX is shown as the Creation TX

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#252]
**Problem**
The incorrect TX is linked from the `test` account's [Detail page](https://explorer.nearprotocol.com/accounts/test) as the creation TX. It appears someone attempted to create an account named `test` after the original account, [this TX failed](https://explorer.nearprotocol.com/transactions/G9W8xFEvrzoFbtiLiVdHG2gZknHs7yP9oy5GA3MdhLkR) (since the name is taken), and this failing TX is now linked. 

**Expected Behavior**
The original, successful account creation TX should be linked from the Account Detail page. 

**Steps to reproduce**

1. Go to https://explorer.nearprotocol.com/accounts/test
2. Click on the Creation Hash

**Comment by frol** [comment]
This bug nature is the same as #223, as we don't have transaction status at the moment when we sync chunks/transactions. We will get unblocked when we actually start saving transaction status with #218.

**Comment by frol** [comment]
Resolved in Explorer baked by the Indexer for Explorer (see #236).
