### ISSUE TITLE
Expose additional aggregate data unavailable over RPC

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#254]
### Overview
We've had requests from third parties to expose more data over the Explorer API.

**Comment by frol** [comment]
@kcole16 We don't have *public* Explorer API. Did we warn those third parties about that? #236 is the way to go.

What kind of data are we talking about? Is it covered in #236?

**Comment by kcole16** [comment]
@frol Right, I named this poorly. Mainly this is a high-level descriptor for #162 (and eventually potentially other data points) that we can display on the roadmap (can only show Epics :/ ).

Perhaps titled "Expose additional aggregate data unavailable over RPC"?
