### ISSUE TITLE
Block #0 should be synced

### ISSUE THREAD

**Issue by frol** [near/near-explorer#262]
Block #0 does not seem to get synced.

## Acceptance Criteria

- [x] The block #0 is synced (if available)
- [x] The Block Details page should display the information correctly for the first block from genesis (the parent block hash should say "Genesis" when `prev_hash == "11111111111111111111111111111111"`)
- [x] Manually tested

**Comment by bowenwang1996** [comment]
Block #0 is always available by the way (unless the node is corrupted).

**Comment by frol** [comment]
@bowenwang1996 Is block #0 available even when `genesis_height` is not zero?

**Comment by bowenwang1996** [comment]
@frol by block #0 I mean genesis block, not the block whose height is actually 0.

**Comment by icerove** [comment]
@bowenwang1996 
when I first try to see block 0 from rpc, I get this: block 0 is correct, block 1 is missing, block 2 is correct ... and then I run the local backend and see the block is actually from 2. 
![image](https://user-images.githubusercontent.com/33007476/80249718-30469500-8627-11ea-9cf9-b36e7ac95502.png)
![image](https://user-images.githubusercontent.com/33007476/80249759-45bbbf00-8627-11ea-9b8d-cece46e85bed.png)
![image](https://user-images.githubusercontent.com/33007476/80249780-4f452700-8627-11ea-894e-a446e0d38393.png)

**Comment by icerove** [comment]
@bowenwang1996 @frol 
I would suggest to see all net we have. There are different problem for different net....

**Comment by bowenwang1996** [comment]
@icerove I don't understand the concern. Some blocks might be missing and that is fine.

**Comment by frol** [comment]
@bowenwang1996 Can you remind me in which cases we can have the same chunk included in several blocks? Can it happen when there are transactions in the chunk? How should this be treated?

**Comment by bowenwang1996** [comment]
@frol I assume you are talking about chunk headers. That happens when there is no new chunk produced.

**Comment by icerove** [comment]
Here is my another confusion:
I query block #1 from mainnet and result is below:
![image](https://user-images.githubusercontent.com/33007476/80259201-e1562b00-8639-11ea-9c9e-554db166fd0f.png)
but mainnet explorer seems have no problem about this block: https://explorer.mainnet.nearprotocol.com/blocks/GnFcZJ5rxctd8qJKocJ2Eq4Um5dLamiiNgMMWsxjEhVL.

Is this normal and correct?

**Comment by frol** [comment]
@icerove Yes, it is seminormal.

1. The blocks and transactions are garbage collected unless you set up a node that does not do that (we set up archival nodes available to Explorer).
2. The error message is fixed in devnet to say Missing Block instead of Not Found when the block is garbage collected.
