### ISSUE TITLE
Update TPS to display different periods of time

### ISSUE THREAD

**Issue by frol** [near/near-explorer#265]
## Story

As a regular user who estimates the capacity of NEAR Protocol, I want to see the stats over some lengthy period of time so I can better understand the picture.

I would like to see the latest TPS (we have it now) and also the peak TPS over 24-hours. There is a metric "load average" on unix systems, which accumulates an average CPU concurrency over 1-minute, 5-minute, and 15-minute periods, so we can just display those TPS as "101 / 17", and put the description in the pop-up help (#237).

## Acceptance Criteria

- [ ] Query backend for Peak 24h TPS
- [ ] Display the value on the dashboard
- [ ] Design fits the numbers up to 9999 TPS
- [ ] Manually tested

**Comment by icerove** [comment]
@kcole16 @frol Can you give more details which peak TPS you actually want to show on the dashboard since Frol gives very different time zones. Should we show 1 minute, 5 minutes or 15 minutes peak TPS over 24 hrs?

**Comment by kcole16** [comment]
The ideal "peak TPS" is identifying the 1 second period in the previous 24 hours with the most transactions and displaying that number. 

I believe @frol is saying we can choose from the unix accumulations (1, 5, 15 min) to calculate this?

**Comment by frol** [comment]
Well, I actually suggested to display several peaks: last 24h / last hour / last minute. I think servers different needs people may have:
* last 24h answers the question: how busy is the network these days?
* last minute: is the network under a heavy load right now? Should I expect delays?
* last hour: was there a spike of load recently?

**Comment by icerove** [comment]
at this point and according to many issues we have that needs design, we should collect them and redesign the board.

**Comment by kcole16** [comment]
> Well, I actually suggested to display several peaks: last 24h / last hour / last minute.

Ah, got it. I do think that is a good idea, but also relatively low priority right now (especially last minute and hour) as our TX volume is very low.

**Comment by frol** [comment]
We decided to remove TPS for now.
