### ISSUE TITLE
Nodes List page should present all the data

### ISSUE THREAD

**Issue by frol** [near/near-explorer#268]
## Story

As a regular user who views Nodes List page, I want to be able to follow the UI and not be distracted or confused so I can better understand the data.

Currently, we have constant reordering on Nodes List page, and the decision to use `last_seen` as an anchor did not play well.

We should come up with a good anchor we can use on the Nodes List page to do pagination and it would be great to preserve the order between update even if the `last_seen` get mixed.

## Acceptance Criteria

- [ ] All the nodes are correctly listed on the Nodes List page
- [ ] There is no jumps / reorderings on the Nodes List page
- [ ] Mobile ok
- [ ] Manually tested

**Comment by icerove** [comment]
I look through the node telemetry data and I think the latest_block_height might be a better anchor to use and will fix with this indexer. @frol

**Comment by frol** [comment]
@icerove `latest_block_height` is also rolling, so it changes between auto-refreshes, so it is also bad anchor

**Comment by icerove** [comment]
okay.
How about fetch all the nodes without limit and implement the pagination from the component? Like the most use case is to give nodelists.slice(0, batchnumber)?

**Comment by frol** [comment]
It defeats the point of pagination...

**Comment by icerove** [comment]
I tried node Id to be the anchor and seems worked fine

**Comment by frol** [comment]
yeah, node_id is fine, at least, it is stable. Though, ordering will look pretty arbitrary :man_shrugging:
