### ISSUE TITLE
fix(frontend): Nodes list loads slowly on switching tabs

### ISSUE THREAD

**Issue by frol** [near/near-explorer#273]
Switching between validating and non-validating tabs on the [Nodes list page](https://explorer.near.org/nodes/validators) takes 10 seconds, so I assume we don't call re-fetch the data immediately and rely on autorefresh handler. We should force fetch the data when switching the tabs

## Acceptance Criteria

- [ ] Nodes list loads quickly on switching the tabs
- [ ] Manually tested

**Comment by icerove** [comment]
I tried this and my fix would be give componentDidUpdate in Nodes.tsx. The situation is this:
first time the data loads for several seconds, but after that it will be quick and no loading. is this okay for you? @frol
