### ISSUE TITLE
Show avg block time

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#277]
Block time is very important property for blockchain that displays how fast tx will be processed and finalized. Would be great to show what has been average block time over last 10 minutes for example.

**Comment by frol** [comment]
@ilblackdragon should it replace TPS? I was planning to display different periods of TPS: #265.

**Comment by frol** [comment]
It is somewhat related to #189, and we need a design for both.

@ilblackdragon Do we want to have it on the dashboard page? I imagine we have an expandable / collapsable widget on the dashboard presenting all the neat details. What do you think?
