### ISSUE TITLE
Trailing URL slash leads to 404

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#287]
### Problem 
Valid URLs with a trailing slash leads to 404 on the following routes. 
- /blocks/
- /accounts/
- /transactions/

Seems to work on:
- /nodes/validators
- /nodes/non-validators

### Expected Behavior
Trailing slash should be ignored and resolve correctly.

### Steps to Reproduce
1. Navigate to explorer.near.org/blocks
2. Add trailing slash to`/blocks/` (explorer.near.org/blocks/)

**Comment by frol** [comment]
It might be nice to have, but it is Next.js issue (https://github.com/zeit/next.js/issues/5214). I don't want to put hacks into our code-base unless we are really desperate. What is the use-case for this?

**Comment by kcole16** [comment]
Got it. Definitely a nice-to-have then. Just to reduce number of 404s people might encounter, certainly not a priority if not a quick fix.

**Comment by frol** [comment]
Should be resolved with https://github.com/vercel/next.js/pull/13333

**Comment by frol** [comment]
Should be resolved with next.js 9.5: https://nextjs.org/blog/next-9-5#optional-trailing-slash-in-urls

@icerove Please, try upgrading to the latest next.js version and confirm that everything works fine and this issue is resolved.
