### ISSUE TITLE
Page reloading when information doesn't exist

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#290]
On https://explorer.betanet.near.org/, when I click some transaction and it shows "information doesn't exist" (presumably it is still syncing actual data), if I go back to dashboard, the page starts to reload again, even though it was loaded before. I am not sure whether this is intended.

**Comment by frol** [comment]
Related to #310.

**Comment by icerove** [comment]
yes, it is intend to do so. when open new pages it will load again and go back also means new pages actually
