### ISSUE TITLE
Display Node on a Geomap based on the IP addresses

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#299]
### Overview
We currently track the IP addresses of nodes in the network in the Explorer, but do not display them. 

The goal of this issue is to create a map view of all validating and non-validating nodes.
Example map would be one here: https://telemetry.polkadot.io/#map/Kusama

<img width="1396" alt="Screen Shot 2020-05-22 at 1 45 48 PM" src="https://user-images.githubusercontent.com/175486/82708211-8dd3fe80-9c32-11ea-8577-e7bc52812860.png">

### Acceptance Criteria
- [x] There is a new page `/nodes/map` which has map view
- [x] All nodes are positioned on the map based on their IP address
- [x] Hover over node provides quick information about it
- [ ] Extra points for animation when nodes are pinging new telemetry information
- [ ] Extra points for animation when validators are producing new block

### Notes
The IP address of the nodes is available via WAMP: https://github.com/near/near-explorer/blob/master/frontend/src/libraries/explorer-wamp/nodes.ts

**Comment by icerove** [comment]
Where should we put IP address to show? /cc @kcole16

**Comment by ilblackdragon** [comment]
Just for context, that's not what I meant.
I meant to add a page where a map with IP-address based locations is shown.

E.g. something like this from Polkadot's telemetry:
![image](https://user-images.githubusercontent.com/175486/82547860-3c7f1e80-9b0f-11ea-9a9d-b496058b6add.png)

Also see milestone 3 here - https://github.com/near/near-explorer/blob/master/spec.md#functionality

**Comment by frol** [comment]
@kcole16 Please, update the description

**Comment by oancius** [comment]
@kcole16  What are the telemetry info that could change (i can think of peer count, but others are pretty static, considering that lastblock is on the other type of animation) You want 2 types of animation or to animate in the same way all the changes?

**Comment by kcole16** [comment]
Quite a few parameters can change (lastSeen, lastHeight, lastHash, agentVersion, agentBuild) but most of these do not need to be animated. 

I think it's fine to have 2 types of animation.

**Comment by oancius** [comment]
@kcole16 k, so just to make sure, can you please describe in a few words the 2 cases that must be animated? As far i understood that 1st case is when a node receives a new block, and 2nd is when anything else changes.

**Comment by kcole16** [comment]
Taking another look at this, I don't think animation is required for anything other than a node coming online/offline. Basically, if a new node comes online, that should "pop up" on the map. And if a node goes offline "pop off". Re: how that animation is implemented and what it looks like, up to you.

**Comment by oancius** [comment]
Got it! Thanks for clarification!
