### ISSUE TITLE
[Bug] Contracts from genesis are not shown

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#300]
## Description
If you open a contract that was deployed in genesis, the account page won't show any contract information.

## Steps to reproduce
1. Open https://explorer.betanet.near.org/accounts/unknown.test
2. Observe that it doesn't show contract information.
3. Check `NEAR_ENV=betanet near state unknown.test` and observe `code_hash: 'DpywzzTNLvpUExfMg8x6yUPuNzEXjQ22D5MpnpKxQunK'`.

**Comment by icerove** [comment]
see this: https://explorer.betanet.near.org/accounts/sebytza05.betanet
I think it is not because it is from genesis. I will look into it

**Comment by icerove** [comment]
For explorer, contract information is actually from transactions table now. In transaction table, since there is no deploy transaction there, the contract could not show. 
If contract info is from genesis, the start point is genesis contains contract. information to query.
/cc @frol

**Comment by frol** [comment]
@icerove We should just display N/A for the transaction hash and last updated. Locked status and the code hash are available for the contracts from genesis.
