### ISSUE TITLE
Untypped Error Bug

### ISSUE THREAD

**Issue by icerove** [near/near-explorer#302]
## Story
As we have this error before, and today I find one of the possibility that after our different net(testnet, betanet, devnet) is reset, some transactions lost but in explorer backend, it is still there, but RPC already not exists. When query transactions from getTransactions function in transactions.ts, the transactions are fetching from the transactions table and when query for transactionExtraInfo from RPC, it will trigger the error "Untyped error".

Example:
https://explorer.betanet.near.org/accounts/unknown.test
the transactions showing on the detail page is 4 and in backend it is 4transaction records there, but when query from RPC, it is like this:
 
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/33007476/82711359-ff637b00-9c39-11ea-9043-74601ce7bf16.png">

## Acceptance Criteria

- [ ] transactions are uniform with backend and RPC
- [ ] proper deal with edge cases
- [ ] Mobile ok
- [ ] Tested

**Comment by frol** [comment]
I forgot to reset betanet after the hard-fork today.
