### ISSUE TITLE
Display more information about the validators

### ISSUE THREAD

**Issue by frol** [near/near-explorer#305]
## Story

As an on-call network engineer who monitors the health of the network, I want to visually distinguish the nodes that last block height is too old or producing fewer blocks than expected so I can quickly build some understanding of the current state of the network.

## Acceptance Criteria

- [x] Change the text color based on how far the last block height reported via telemetry from the last block height we know (if the difference is more than 1000, display the last block height in red, >50 - orange)
- [x] Display the produced / expected blocks (display the raw numbers + percentage). Expose the `validators` API to fetch the `current_validators` list via Explorer backend
- [ ] Let's try to write end-to-end tests for these cases using the cypress facility we have configured

**Comment by icerove** [comment]
for step 3, test part. Would you mind tell more details and hint? @frol

**Comment by frol** [comment]
@icerove see into https://github.com/near/near-explorer/blob/74b1cb84f4821b54a2b8e5fe20c06e1a16f15c10/frontend/cypress/integration/dashboard.spec.js. You run end-to-end tests with `npm run test:ci`. Otherwise, learn more about Cypress and read `frontend/package.json` scripts.
