### ISSUE TITLE
Improve pagination animation

### ISSUE THREAD

**Issue by th3m477** [near/near-explorer#306]
Frontend only.

When scrolling and loading more content (or via "Load more" buttons) with `FlipMove`, for example on the Transactions tab, the animation is frustrating.

Google Chrome on macOS: Version 81.0.4044.138

![pagination](https://user-images.githubusercontent.com/3482256/82931409-cb13f580-9f7e-11ea-9cfa-b181b7b950e1.gif)

**Comment by th3m477** [comment]
Related but not specific: https://github.com/near/near-explorer/issues/294

**Comment by frol** [comment]
@th3m477 Thank you for bringing it up! We definitely feel that the pagination story is not well-solved. I don't have that momentum scrolling effect. Is it Safari? Do you by any chance have an idea of how we can improve it?
