### ISSUE TITLE
Validator vs non-validator are possibly wrong

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#308]
Observing 82 validators but only 50 nodes shown in explorer.
Additionally, validators are shown in non-validating nodes.

<img width="785" alt="Screen Shot 2020-05-30 at 2 54 02 PM" src="https://user-images.githubusercontent.com/175486/83339743-8d1c1780-a285-11ea-9f1d-b1a3e224b49e.png">

One explanation, is that node is running with incorrect keys, might be worth to highlight it in that case to inform that signatures for this account doesn't match.

**Comment by bowenwang1996** [comment]
@ilblackdragon I think it is because some nodes fail to report telemetry correctly. We still don't know why this happens.

**Comment by kcole16** [comment]
@bowenwang1996 @frol  Is there any way we can detect that on the RPC/Explorer side?

**Comment by frol** [comment]
> Observing 82 validators but only 50 nodes shown in explorer.

As Bowen pointed out, it is a known issue (https://github.com/nearprotocol/nearcore/issues/2798) that I fail to reproduce and catch.

> Additionally, validators are shown in non-validating nodes.

That is odd and is a complete mystery. That is how they report themselves. I believe that is a configuration issue.

**Comment by bowenwang1996** [comment]
> That is odd and is a complete mystery. That is how they report themselves. I believe that is a configuration issue.

That is because the node is still syncing and at their current head they are not a validator.

**Comment by icerove** [comment]
fixed #339
