### ISSUE TITLE
Show stake for validators

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#309]
In the list of validators, it would be good to show the current stake of the validators.

Also, if the account confirmed (signed), which is true for validators - make it clickable for details.

**Comment by kcole16** [comment]
@frol @icerove Do we have stake readily available to display in this list?

**Comment by frol** [comment]
Yes, we can query [`validators` from RPC](https://docs.near.org/docs/interaction/rpc#validators) (see `current_validators`)
