### ISSUE TITLE
Configure the monitoring of Explorer production services uptime

### ISSUE THREAD

**Issue by frol** [near/near-explorer#315]
## Story

As a maintainer who deploys Explorer, I want to be notified immediately when the services go offline so I can provide uptime SLA.

## Acceptance Criteria

- [x] Frontend monitoring endpoints are implemented (@icerove)
- [x] Backend monitoring endpoints are implemented (@icerove)
- [x] Frontend monitoring is configured on statuspal.io (@frol)
- [x] Backend monitoring is configured on statuspal.io (@frol)
- [x] Tested (@icerove & @frol)

## NOTES

- let's have `nearcore-status` WAMP endpoint on the backend
- let's have `GET /api/status` endpoint on the frontend (just add `status.js` file in the `frontend/src/pages/api/` folder) which calls the backend `nearcore-status` WAMP endpoint.
- let's have two checks:
  1. Frontend availability check with a GET request to the dashboard: `GET /`
  2. Backend availability check with a GET request to the `GET /api/status` API, which will go through the whole stack (frontend -> backend -> RPC) and back
- Should we use https://nearprotocol.statuspal.io/ or should we have a separate statuspal page for Explorer? In that case, we clearly decouple the blockchain from the AppLayer /cc @kcole16 @vgrichina @ailisp @chefsale

**Comment by ailisp** [comment]
> Should we use https://nearprotocol.statuspal.io/ or should we have a separate statuspal page for Explorer? In that case, we clearly decouple the blockchain from the AppLayer /cc @kcole16 @vgrichina @ailisp @chefsale

I think rpc.testnet.near.org is also kind like "applayer", it's like our official infura, which if we're decentralized enough, they're down doesn't relevant to the network is down, so I think it makes sense to use the same statuspal. We should use explorer node page as our "network status"

**Comment by frol** [comment]
@ailisp Good point! I agree with that.

**Comment by frol** [comment]
Configured as sub-services: https://status.nearprotocol.com/
