### ISSUE TITLE
Unable to recover wallet on mobile browser

### ISSUE THREAD

**Issue by htafolla** [near/near-explorer#325]
When recovery your wallet on a mobile browser it gives the error: Please match the requested format

The error refers to the seed phrase. I have made sure that there were no spaces before or after the phrase and I have tried Brave, Chrome and Kiwi.

**Comment by frol** [comment]
Issue moved to [near/near-wallet #652](https://github.com/near/near-wallet/issues/652) via [**ZenHub**](https://www.zenhub.com/)
