### ISSUE TITLE
Missing ID in one of the DB records 

### ISSUE THREAD

**Issue by vgrichina** [near/near-explorer#328]
One of the records in explorer DB seems weird:

```
action without hash_with_index {
  hash_with_index: null,
  kind: null,
  args: null,
  signer_id: 'xyjnear.testnet',
  receiver_id: 'xyjnear.testnet',
  block_hash: '5zEu2yGYwR8uA41hdMnGs1fiBfGuKugUPoxqXkFpZw1C',
  block_timestamp: 1590116295176
}
```

**Comment by frol** [comment]
There are no actions in the transaction. I send you the details in PM since our public RPC nodes garbage-collected the data already.

**Comment by frol** [comment]
I believe, the only reason you observe the nulls is due to JOINs.
