### ISSUE TITLE
fix(frontend): The fees needs to be computed based on the amount_burnt

### ISSUE THREAD

**Issue by frol** [near/near-explorer#333]
## Story

https://github.com/nearprotocol/nearcore/pull/2813 and https://github.com/nearprotocol/nearcore/pull/2872 introduced dynamic gas pricing and a new field `amount_burnt` should be used to correctly reflect the fees.

## Acceptance Criteria

- [x] The transaction fee is computed as a sum of `tokens_burnt`
- [x] Gas price should be removed from the Transaction Details page as it dynamic over time and the gas price on a single block is not representative for a transaction fee
- [x] Reviewed by @evgenykuzyakov 

## Notes

https://github.com/nearprotocol/nearcore/pull/2872 is not merged yet, so there is no field in the RPC yet. Thus, this issue is blocked at the moment.

@evgenykuzyakov Please, review the plan for the changes on Explorer, so we are on the same page here.

**Comment by evgenykuzyakov** [comment]
> The transaction fee is computed as a sum of `amount_burnt`

Correct. Renamed the field into `tokens_burnt`. 

> Gas price should be removed from the Transaction Details page as it is not used

True.

>   The changes are backwards compatible, so mainnet, testnet, etc still work using the simple `gas_burnt * gas_price` formula

I assume this is for legacy deployed chains. Yes. The total `tokens_burnt` can be calculated from the sum of `gas_burnt * gas_price`

NOTE: We should still display total gas burnt and total prepaid gas amount as before.

**Comment by kcole16** [comment]
@frol Do you still think we should remove "Gas Price"? Seems like this is still dynamic, correct?

See #364 for changes @ilblackdragon is suggesting to Gas Price.

**Comment by bowenwang1996** [comment]
> Do you still think we should remove "Gas Price"? Seems like this is still dynamic, correct?

It is dynamic, but why should we remove it? I agree that we should display it better though.

**Comment by icerove** [comment]
- [ ] The transaction fee is computed as a sum of `tokens_burnt`

**Comment by frol** [comment]
> I agree that we should display it better though.

Once we have NEAR Indexer for Explorer (/cc @khorolets) we will be able to break down the gas price to the receipts granularity and then it will make sense, but currently, displaying a single value based on the initial block is not useful anyway, and I would even say that it is misleading and thus harmful.

**Comment by bowenwang1996** [comment]
I see. That makes sense.

**Comment by icerove** [comment]
okay, I get that.
