### ISSUE TITLE
repetitive error message on Account Not Found page

### ISSUE THREAD

**Issue by chadoh** [near/near-explorer#336]
When you visit an account page for a non-existent account such as https://explorer.testnet.near.org/accounts/vanilla, the error you see repeats itself three times:

![Information is not available at the moment. Please, check if the account name is correct or try later. Information is not available at the moment. Please, check if the account name is correct or try later. Transactions Information is not available at the moment. Please, check if the account name is correct or try later.](https://user-images.githubusercontent.com/221614/85763870-16870400-b6e3-11ea-8ca5-005b7c163163.png)

---

Maybe it would make sense to change the main heading and show a single error there?

**Comment by icerove** [comment]
a duplicate issue of #310
