### ISSUE TITLE
Rework Validators page

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#339]
Validators page should provide info about all validators not just validators that are currently reporting telemetry validators. Telemetry should just augment information from `validators` RPC (accessible via `provider.validators()`).

Additionally, there should be information about epoch progress on the top (similar to main page dashboard), avg. block time, total amount of stake, current stake price.

Also in the list of validators show ones that are going to be kickedout in the next epoch / new coming and also upcoming proposals. This can be shown in the single list indicating with color and icons on the status.

A really nice UI: http://solanabeach.io/

Specifically for epoch progress:
<img width="330" alt="Screen Shot 2020-06-26 at 10 22 22 AM" src="https://user-images.githubusercontent.com/175486/85884110-eef17380-b796-11ea-840a-6e0b83a96607.png">

For listing validators and their stake distribution:
<img width="1122" alt="Screen Shot 2020-06-26 at 10 22 57 AM" src="https://user-images.githubusercontent.com/175486/85884147-04669d80-b797-11ea-8de6-2cad800ff191.png">

**Comment by frol** [comment]
We should invert the logic for the validation nodes listing. Currently, we fetch the list of validators from the Nodes table which is based on the telemetry data, which is not accurate, may have old nodes that believe that they are validators (we should check that when receiving telemetry data, but we don't do this yet). Instead, we should use the information from RPC (`current_validators` on `validators` API), and augment it with the telemetry data (Nodes table)

**Comment by icerove** [comment]
@frol should I close current PR and start a new one for this?

**Comment by frol** [comment]
@icerove I think we don't need to close #331, but we should extend it with the ideas suggested here. Why do you think we should close #331?

**Comment by ilblackdragon** [comment]
Agree with @frol - we should continue #331 and just display current validators from RPC augmented with Nodes data instead of the other way. 

Also I didn't do a good search before filling this, should have linked #309 and #305

**Comment by zavodil** [comment]
Epoch details info was added to the https://t.me/nearup_bot (command /epoch) with full information and graphical representation

**Comment by icerove** [comment]
@ilblackdragon 
where can we get the epoch information?

**Comment by icerove** [comment]
related with #308
