### ISSUE TITLE
fix(frontend): Fresh page load of pages with autoRefreshHandler should load fine on initial load

### ISSUE THREAD

**Issue by frol** [near/near-explorer#341]
## Story

As a user who opens Blocks / Accounts / Dashboard / Nodes by a direct link, I experience problems with page loads as the rendered content appears for a brief moment and immediately replaced with a loading indicator, and the list of data gets finally rendered only in 10 seconds (when the next iteration of autoRefreshHandler happens).

## Acceptance Criteria

- [ ] The pages load fine when opening them via direct link
- [ ] The pages load fine when opening them via client-side routing (it works fine now, but we should make sure we don't introduce degradation)

**Comment by icerove** [comment]
@frol The problem is not about the autorefresh handler, it is about _app.js file: https://github.com/near/near-explorer/blob/06bce5cf6e6d77165fa4e4c5b90255e7804ffdc0/frontend/src/pages/_app.jsx#L53

before we do not have componentDidMount function is this file and now after we have this, every time open the website from direct link, this one will trigger twice when finaStamp is really fetched, so it appears like what you describe in the comment. We maybe cannot use Context to contain the finalStamp and lastBlockHeight, which need promise to fetch data and trigger render. What do you think?

**Comment by frol** [comment]
Well, we have a few problems here:

1. It seems that we have some state/render problems down the line when the *Provider components get re-rendered due to the changes. Why? Can you investigate further?
2. We don't want to re-render the whole app when we update the value, so I suggest we give https://recoiljs.org/ a try
3. Also, I did not catch it before, but we need to `fetchFinalStamp` regularly, not only on the first mount

**Comment by icerove** [comment]
> We don't want to re-render the whole app when we update the value, so I suggest we give https://recoiljs.org/ a try
I look through recoiljs and think it is the same as react hooks and it is applied most of functional component. Now we use state component and I remember you do not very like hooks, should we really give this a try? From my side, I am not refusing to change the style but does it worth it? @frol

**Comment by icerove** [comment]
> It seems that we have some state/render problems down the line when the *Provider components get re-rendered due to the changes
What exactly is the problem? can you tell me how to reproduce?

**Comment by icerove** [comment]
Here is my thinking for explorer fetching data logic for explorer(not only for this issue but related): WAMP sync and store the data in the database table. The frontend api query the lists(transactions, blocks and accounts) from the table using methods and doing this every 10 seconds. I realize that this will trigger problems like this issue we will have. WAMP has substitute function, why we not letting the frontend sub the data and in this way, when there is new data, or some data updated, the frontend will render for them. This logic makes more sense and we will not having autorefresh logic in the frontend.
@frol

**Comment by frol** [comment]
@icerove yeah, hooks API & functional components are the requirements for recoiljs, but only for the components where it uses it, so we can live with that, I guess. I am not particularly happy, but I don't see a good alternative.

> What exactly is the problem? can you tell me how to reproduce?

I believe we have some problems with our "componentDidUpdate" or some other component lifetimes, I don't know the exact reason, but the observation (update of the context leads to re-render and does not really succeed, so it only recovers 10 seconds later with the next auto-refresh) suggests that it is the case.

> WAMP has substitute function, why we not letting the frontend sub the data and in this way, when there is new data, or some data updated, the frontend will render for them. 

Do you mean "subscribe" instead of "substitute"? So you suggest the frontend listens to the new data instead of polling it, right? We can easily implement that for the general lists like a list of all transactions, a list of all blocks, but that is not going to work well for a specific account page, as there are too many of them and we should only push events to those who are interested in the event, otherwise it is a waste of resources.
