### ISSUE TITLE
【Bug submit】I use near view to see, my 75639 tokens are staked. But the explorer show 75639 token are unstaked

### ISSUE THREAD

**Issue by youlaiwuqu** [near/near-explorer#347]
I use near view to see, my 75639 tokens are staked. But the explorer show 75639 token are unstaked. I refresh the webpage many times. But it still shows the 75639 tokens are unstaked.
https://ibb.co/Tw9yDPZ
https://ibb.co/CBcwBZ5

**Comment by frol** [comment]
@youlaiwuqu  Thank you for bringing this up! Currently, we don’t support delegation contracts in Explorer, which means that we only display the native staking. We are going to address this after we migrate to the new Network Indexer backend (#236)

**Comment by frol** [comment]
Wallet Profile page is going to be the right place to look up for the delegated (aka "staked") balances. A direct link is available on Explorer Account page now.
