### ISSUE TITLE
Failed transaction is shown as success

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#358]
There is a problem how to define which transactions are success and which ones are failure when there are receipts and callbacks.

We need to figure out a standard where if originator received failure and returned false - we should show that transaction failed.

E.g. https://explorer.near.org/transactions/DpiLFUsvgFH7vx5GCF2fRauynDwHweVWN96A3NVdFZv5
We call near.create_account_and_claim which created a receipt to create account - which failed and then callback was called in near.on_create_account_and_claim which returned false (receipt `9uy8ELW...`) to indicate that this process failed.

**Comment by frol** [comment]
First, we mislead people about “successfulness” of transactions as there is no way to clearly define what should be considered a successful transaction (https://github.com/near/near-explorer/issues/212#issuecomment-656623756, see (3)), so we are going to replace it with “in-progress” & “completed”.

Second, we need the new Explorer Indexer (https://github.com/near/near-explorer/issues/236) to resolve issues like this and https://github.com/near/near-explorer/issues/223

**Comment by frol** [comment]
Resolved in Explorer baked by the Indexer for Explorer (see #236).
