### ISSUE TITLE
Some account is missing from the account page

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#359]
On mainnet explorer account page https://explorer.mainnet.near.org/accounts does not show this account https://explorer.near.org/accounts/bowen.near for some reason.

**Comment by frol** [comment]
@bowenwang1996 How was it created? Was it created from a contract? Current Explorer indexing does not include information from receipts, this was the motivation to implement Network Indexer (#236) in the first place.

**Comment by bowenwang1996** [comment]
No, I believe @ilblackdragon created the account through a foundation account.

**Comment by icerove** [comment]
this account showing no created and creation hash at all which is really weird, and the transaction on that page is also strange and cannot read information from that transaction. This error probably happen from nearcore not from explorer. @frol @bowenwang1996

**Comment by frol** [comment]
My current guess is that the RPC node that is used by Explorer does not have the relevant transaction (either it GCed it [we should use archival nodes] or the node was offline during the event).

**Comment by bowenwang1996** [comment]
@frol the nodes were all online. I guess the issue is probably that the transactions are gc'ed, although I thought explorer will index them locally.

**Comment by frol** [comment]
It is now in genesis, and I can see `bowen.near` on the accounts list page and also by the direct link, so I have no idea what was wrong. Explorer does index the accounts locally if those are created in genesis or via a transaction (it is incorrect, as we should rely on receipts and execution outcomes confirming that the receipt execution was successful)
