### ISSUE TITLE
Confusing non validators page

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#360]
Steps:
1. Open https://explorer.testnet.near.org/nodes/non-validators
2. Observe that all non-validating nodes are marked as "Staking"
3. Even though most of these accounts don't even have "locked" balance, not even that they are actually have proposals or next validators.

<img width="1114" alt="Screen Shot 2020-07-20 at 2 15 24 AM" src="https://user-images.githubusercontent.com/175486/87921354-49e15800-ca2f-11ea-931e-13cfdd27d729.png">

**Comment by frol** [comment]
This should be resolved in #339. @icerove am I right?

**Comment by icerove** [comment]
you are right and we already change that into validators and online nodes.

**Comment by icerove** [comment]
fix by #349
