### ISSUE TITLE
Change gas price in tx details to N/Tgas

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#364]
It's expected that gas prices will always be far below 0.00001 N, because we measure gas in "Giga" and "Terra"
Ideally we should show gas price in $NEAR/Terra Gas or Giga Gas.

Generally I use "Tg" or "Gg" as identifiers for this -> "Gas Price Ⓝ/Tg". 

Our min gas price is 1,000,000,000 yN / g or -> (1,000,000,000 * 1,000,000,000,000)/1e24 = 0.001 Ⓝ/Tg

Tooltip can explain this and show the raw gas price if required.

**Comment by kcole16** [comment]
Title: ```Gas Price```

Value: ```0.001 Ⓝ / Tgas```

Tooltip text: 
```
A unit of Tgas (TerraGas) is 1*10^12 units of gas. The costs of gas are very low in terms of NEAR, which is why Tgas is more commonly used.
```

**Comment by icerove** [comment]
decide to delete gas price so far, will get back when indexer implementation.

**Comment by icerove** [comment]
it is applied to the block detail page instead
