### ISSUE TITLE
Node map is not displaying online validating node directly

### ISSUE THREAD

**Issue by nearmax** [near/near-explorer#368]
Go to https://explorer.testnet.near.org/nodes/map and observe an empty map
Users have to click the button to see the node on the map

Expected: not empty map on first glance

**Comment by icerove** [comment]
@nearmax I am already start fixing this and thanks to mention

**Comment by frol** [comment]
I don't think it is fair to say that this is fixed as we currently require a user to click on one of the two buttons ("online Validating nodes" | "Online nodes") as per https://github.com/near/near-explorer/pull/378#discussion_r469627939.

I decided to merge the initial version of the implementation now to address this smaller UX issue in a separate PR.

**Comment by icerove** [comment]
Even though you merge the initial version, why do you also change ip fetching part? it still uses `http` not` https`. and also it still require to click the button to see node on map

**Comment by icerove** [comment]
maybe a better solution is if you have some time, touch this and fix. @frol

**Comment by luixo** [comment]
Seems like we don't have map at the moment, feel free to reopen issue if map will get back to Explorer
