### ISSUE TITLE
Dashboard stats are never loaded

### ISSUE THREAD

**Issue by frol** [near/near-explorer#377]
mainnet:

![image](https://user-images.githubusercontent.com/304265/89431630-90fd6780-d716-11ea-9656-8826a67bba9f.png)

betanet:

![image](https://user-images.githubusercontent.com/304265/89431670-9bb7fc80-d716-11ea-98b5-2df88b02297b.png)

testnet:

![image](https://user-images.githubusercontent.com/304265/89431533-75925c80-d716-11ea-9475-54847a0d00dd.png)

It spins like that forever.

**Comment by icerove** [comment]
It is back now since I redeploy.
