### ISSUE TITLE
Resizing the nodes page leads to UI bug

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#379]
Please see screenshot at the smaller resolution of the page:

<img width="866" alt="Screen Shot 2020-08-10 at 9 05 06 AM" src="https://user-images.githubusercontent.com/175486/89804235-be685d80-dae8-11ea-9b1a-c572ffede0d9.png">

**Comment by icerove** [comment]
what bug? I put the two button to the bottom since if at top, it will block the header

**Comment by icerove** [comment]
do you mean the footer is disappeared? @ilblackdragon
