### ISSUE TITLE
Transaction fee popup should not be empty

### ISSUE THREAD

**Issue by frol** [near/near-explorer#383]
https://explorer.near.org/transactions/7aZRyvfRnZzMQtxmxvMnTGmrdR44osAnRhady5ZE39EY

Hover over the transaction fee and observe that currently it is empty.

![image](https://user-images.githubusercontent.com/304265/90028143-b1d23980-dc8f-11ea-86ce-6ebb9319ea89.png)

**Comment by icerove** [comment]
well, this is copied from wallet which I think wallet forgets to deal with this case. @frol
