### ISSUE TITLE
Viewing transactions on an account page shows wrong account when scrolling

### ISSUE THREAD

**Issue by mikedotexe** [near/near-explorer#388]
I was here looking for transactions on my account:
https://explorer.testnet.near.org/accounts/oracle-node.p.mike.testnet

and as I scrolled down I started seeing transactions from another account that was not mine. Something seems to be wrong with the paging/infinite-scroll.

<img width="790" alt="Screen Shot 2020-08-17 at 9 55 27 PM" src="https://user-images.githubusercontent.com/1042667/90472146-b30ec680-e0d4-11ea-8e96-775834d9b268.png">

**Comment by icerove** [comment]
@mikedotexe good catch! Thank you for using explorer. Will fix it ASAP

**Comment by mikedotexe** [comment]
Thank you! 🙌🏼
