### ISSUE TITLE
Migrate away from EXPERIMENTAL_genesis_records

### ISSUE THREAD

**Issue by frol** [near/near-explorer#393]
nearcore wants to shrink down the RAM usage and genesis records are huge to keep in memory all the time, so nearcore wants to deprecate the `EXPERIMENTAL_genesis_records`. Instead of getting the genesis records from the RPC we can download the genesis.json file for the relevant network from S3 and load the records from it.

* https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/betanet/genesis.json
* https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/genesis.json
* https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/mainnet/genesis.json (not available at the moment, but I believe it will be /cc @bowenwang1996)

Notes:
* The genesis file can be gigabytes of JSON, and that may introduce some issues due to the RAM usage (just be ready). Ideally, we want to have a way to scan it through and iterate over the records without reading all of them into memory all at once
* There can be the case that there is no genesis.json for some networks available on our S3 (e.g. when we run a local node network), Explorer backend should just log a warning and keep going

**Comment by ailisp** [comment]
>  The genesis file can be gigabytes of JSON, and that may introduce some issues due to the RAM usage (just be ready). Ideally, we want to have a way to scan it through and iterate over the records without reading all of them into memory all at once

I think this is very likely, we've tried load genesis json (300M) in a 1 GB instance in python, and failed due to run out of memory. We should load json locally and store it in render's database. But do we have a way to access render sqlite db locally?

**Comment by icerove** [comment]
render.com does not allow us to change database file and we have to get the json file as the first step which will run out of memory and have no method to control it

**Comment by bowenwang1996** [comment]
> in a 1 GB instance in python

Couldn't we use a more power instance?

**Comment by icerove** [comment]
> We want to keep regularCheckGenesis, but we don't need regularSyncGenesisState (just do it once on start and if it fails, log the error message and exit immediately).

do we still keep genesis config in the nearcore? I see the json file have all config and records. @frol

**Comment by bowenwang1996** [comment]
Yes the endpoint `EXPERIMENTAL_genesis_config` will still exist.

**Comment by icerove** [comment]
for mainnet. will use this link: https://github.com/nearprotocol/nearcore/blob/master/neard/res/mainnet_genesis.json for this time. If it is changed in the future, will change it directly in the file on render backend server
