### ISSUE TITLE
Display Phase 2 vote current status

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#416]
### Overview

To indicate to community members the progress of the vote towards Phase 2, we can visualize the current status of the vote in a progress bar.

The progress can be represented as a % of the vote needed to enable Phase 2. 

**Example**
- Total stake = 600M
- Total votes = 200M (1/3 of total stake)
- Amount needed to enable Phase 2 (2/3 of total stake) = 400M

```
Current Status of the Vote to Enable Phase 2 (2/3 of Total Stake is Needed)

|---------->                      |              
        200M Voted           400M Needed (2/3)              

```

**Technical Implementation**

Two functionCalls to the [voting contract](https://github.com/near/core-contracts/blob/cd221798a77d646d5f1200910d45326d11951732/voting/src/lib.rs)
- Total stake = `get_total_voted_stake()`
- Total votes = `get_votes()`

Calculations
- Total votes needed = `total_stake * (2/3)`
- % of total stake currently voted = `(total_votes / total_stake) * 100`

### Acceptance Criteria

- [x] Total stake (in NEAR) is displayed
- [x] Total votes (in NEAR) is displayed
- [x] Total votes needed (in NEAR) is displayed (2/3 of total stake)
- [x] % of the votes needed to launch Phase 2 is visualized in the progress bar
- [x] Mobile ok
- [x] Tested

**Comment by icerove** [comment]
@kcole16 we should use the data from the contract or we should write our own in the explorer and make voting as refer?

**Comment by evgenykuzyakov** [comment]
Account is https://explorer.near.org/accounts/transfer-vote.near

**Comment by icerove** [comment]
thanks

**Comment by icerove** [comment]
it is empty now. 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/33007476/92965262-529c4c00-f42a-11ea-88f5-903d010e75e2.png">

**Comment by evgenykuzyakov** [comment]
Yes. No one voted on mainnet yet. You can use `vote.f863973.m0` on testnet for testing.

**Comment by icerove** [comment]
I finish the backend query and need to wait for design and where to display for this

**Comment by kcole16** [comment]
@corwinharrell 
1. As long as the vote takes + 3 days or so. @bowenwang1996 @jimmy3dita What do you think?
2. Agreed, updated the issue to reflect this

**Comment by bowenwang1996** [comment]
> As long as the vote takes + 3 days or so. @bowenwang1996 @jimmy3dita What do you think?

It's hard to say right now but that sounds more or less reasonable. Even if it ended earlier we can still persists it for a bit longer.

> we should indicate that the required vote is 2/3 of the total stake, or a specific amount

We should use percentage rather than the amount because total staked amount can change between epochs.

**Comment by icerove** [comment]
I have a suggestion: we show total amount as whole bar and give complete amount(2/3) to have a line there. Like this:
|---------->                                                             |                                                       |
        200M Voted                                        400M Needed (2/3)                               600M total
