### ISSUE TITLE
Accounts number / list on mainnet explorer is missing most of accounts

### ISSUE THREAD

**Issue by vgrichina** [near/near-explorer#418]
See https://explorer.near.org/accounts

There are far more accounts on mainnet right now than listed there. I guess accounts from linkdrop aren't getting indexed?

**Comment by frol** [comment]
Yeah, it all stems from the lack of receipts indexing (#218), which causes issues like this and #223 and #358.

Thank you for bringing it up. Indexer for Explorer will resolve a bunch of issues like this.

**Comment by frol** [comment]
Resolved in Explorer baked by the Indexer for Explorer (see #236).
