### ISSUE TITLE
Localization (l10n) and internationalization (i18n)

### ISSUE THREAD

**Issue by frol** [near/near-explorer#42]
It is a placeholder issue tracking our future efforts around multi-lingual support in NEAR Explorer

**Comment by vgrichina** [comment]
@frol do you think https://ryandrewjohnson.github.io/react-localize-redux-docs/ is a solid solution?

**Comment by frol** [comment]
@vgrichina it looks good, but I have not validated alternatives yet. Do you have experience with this particular module or other models for l10n & i18n?

**Comment by vgrichina** [comment]
@frol don't have experience yet, but plan to try it soon for wallet. I like that it allows you to provide HTML/React translations as well.

**Comment by frol** [comment]
Just bumped into another alternative: https://lingui.js.org/
