### ISSUE TITLE
Update NEAR logo

### ISSUE THREAD

**Issue by frol** [near/near-explorer#424]
https://near.org/downloads/NEAR_PressKit.zip

* [ ] Logo in the top Left corner (Desktop layout of Explorer)
* [ ] Logo in the top Left corner (Mobile layout of Explorer)
* [ ] Favicon

**Comment by icerove** [comment]
I think it is black one and not white one.

**Comment by icerove** [comment]
since we are going to implement new home page next week, and this is included, I do not think it is good to do so.
