### ISSUE TITLE
Implicit accounts don't have any data about creation

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#425]
For example https://explorer.testnet.near.org/accounts/1b3107c66e0ad2f3e4054c2f9d81d9d60f4254b86adc204fa5dac345a193f264

Doesn't have created date.

Implicit accounts are created via transfer of money to the account that didn't exist before with length of ID 64 and being a hex of the public key.

**Comment by icerove** [comment]
I think this one is fair enough to be include into the indexer instead of current backend. @frol @khorolets 
What do you think?

**Comment by frol** [comment]
I agree with @icerove

**Comment by frol** [comment]
Resolved in Explorer baked by the Indexer for Explorer (see #236).
