### ISSUE TITLE
Some incoming function calls are not shown

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#428]
For example, there are definitely more incoming function calls to this account - https://explorer.near.org/accounts/transfer-vote.near but they are not shown in the history.

**Comment by frol** [comment]
@ilblackdragon Are they [function calls] triggered as cross-contract calls? (duplicate of #323?)

**Comment by bowenwang1996** [comment]
Yes I believe it is the same issue (action from receipts not being properly indexed).
