### ISSUE TITLE
"Access key added" doesn't describe which key is added

### ISSUE THREAD

**Issue by vgrichina** [near/near-explorer#436]
When I view transaction which added / removed key – it is interesting which key was removed/added and with which permissions.

It is currently not visible https://explorer.near.org/transactions/DmAncJcrxCt4mPFmbmvdc8E3RfQbhTdSisoJ5Mmyzaok

**Comment by frol** [comment]
@icerove Let's update our template for detailed action view to include the public key and information about permissions (full access or function-call only with the method name(s)) and nonce
