### ISSUE TITLE
Incorrect display of actions

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#437]
In this transaction https://explorer.near.org/transactions/8YFhKbDbsVvmWz9HccyiBtKPUnPpztJ3NXHapnqSjvyd, explorer shows that access key is added for `fish.poolv1.near`, which is impossible since `fish.poolv1.near` is a staking pool and no access key can be added to it. A check on the state of the account confirms this.

**Comment by ilblackdragon** [comment]
This is not what explorer says.
Explorer says that a new key was added to account `bcd38. . .d662e666c05ca9c` with permissions for calling actions on `fish.poolv1.near` contract.
It's not a bug, but we should make the messaging clearer.

**Comment by frol** [comment]
If you have a better message in mind, just let us know

**Comment by icerove** [comment]
same as #436

**Comment by frol** [comment]
@bowenwang1996 is it any better now? (the fix is deployed)

**Comment by bowenwang1996** [comment]
@frol yes
