### ISSUE TITLE
Add information about block producer

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#441]
Currently block producers don't have information outside of the pool's name.

There is missing useful information such as: links to seats / fees / rewards / website / social links / profile pic / location / etc.
 
See for example https://bloks.io/

<img width="1150" alt="Screen Shot 2020-10-06 at 2 47 14 AM" src="https://user-images.githubusercontent.com/175486/95185943-403dd580-077e-11eb-8415-da2d7d199949.png">

**Comment by frol** [comment]
I am closing this in favor of #370. Please, see my questions there.
