### ISSUE TITLE
Minor adjustments to how addition of keys is displayed

### ISSUE THREAD

**Issue by vgrichina** [near/near-explorer#446]
There are few minor issues:
1. There is no point to show  "and nonce 0", as it is always 0 for newly added key.
2. When method list is empty, it is important to highlight it is a permission to call "any method" (see here https://explorer.near.org/transactions/DVFzw4v1mBr2ibjzyJX3iz9imxkfpaRgULzgxcBEeFVJ)
3. It's best if method names are separated with comma + space. Otherwise text doesn't wrap properly when there is longer list and you reduce window size, e.g. here https://explorer.near.org/transactions/FeQZB6E381n66qRmtXnLV9jEqNF1KAn8zCiq42XMAmej
4. Not sure if brackets around methods list are intentional.

**Comment by frol** [comment]
1. That is not true. You can add a key with a non-zero nonce, it should be used when you are re-adding previously removed key and you want to avoid replay attacks
2, 3, 4. These are valid concerns! @icerove Could you address those?
