### ISSUE TITLE
Results are displayed in base64 even when it is valid JSON

### ISSUE THREAD

**Issue by vgrichina** [near/near-explorer#449]
See for example:
https://explorer.near.org/transactions/9iM4XWaqJD5GPvHRhj7t5jVoJvobbrmAgh4GE149K3q6

Result is displayed as `MQ==` (i.e. base64-encoded) even though it is valid JSON: `1`

I think result should be displayed as JSON if it's parseable and as hexdump otherwise (i.e. similar to arguments).

Ideally should be possible to switch to hexdump explicitly as well (as binary stuff might be accidentally parsable as JSON).

**Comment by frol** [comment]
Resolved in #518
