### ISSUE TITLE
Geo map issues

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#453]
Geo map has next issues https://explorer.near.org/nodes/map:
 - there is server with location of "null" put in the middle of the map
 - it seems like there is grouping happened around random points on the map when there is no specific location provided
 - specifically, there is middle of US point with lots of servers and same somewhere in eastern europe
 - when opening a detailed around server, the only way to close it is to click on another point. It should close when clicking on other places on the map and should if clicked on another point should open it's list (right now it just closes previous one)
 - not all points hovering works as well
 - when there is a list, it should be good to on hover to see something as well
 
<img width="1110" alt="Screen Shot 2020-10-16 at 4 23 33 AM" src="https://user-images.githubusercontent.com/175486/96252775-5c542a80-0f67-11eb-8211-2606274bc396.png">

**Comment by icerove** [comment]
will fix after migration indexer

**Comment by luixo** [comment]
Seems like we don't have map at the moment, feel free to reopen issue if map will get back to Explorer
