### ISSUE TITLE
Roll back the detailed balances on Explorer in favor of Wallet Profile link

### ISSUE THREAD

**Issue by frol** [near/near-explorer#464]
## Story

Based on the discussion here: https://github.com/near/near-explorer/discussions/463

We decided to take a step back on the Explorer side to avoid the rabbit hole we can get trying to pull out all the balances the account may have in various contracts. Instead, Explorer is going to focus on the native NEAR network features and Wallet will provide the user-facing breakdown and control over the assets.

## Acceptance Criteria

- [ ] ~Account Details page only contains the Non-staked balance, Staked Balance, and Minimum Balance~ UPD: @khorolets and I decided to avoid any balances on Explorer side and only provide the link to Wallet Profile
* [ ] ~Minimum Balance should be visually linked with the Storage Usage (since Minimum Balance is computed based on the Storage Usage and storage amount per byte)~ UPD: see above
- [x] There should be a link to the Wallet Profile page (``` `$[nearWalletProfilePrefix]/$[accountId]` ``` -- add `nearWalletProfilePrefix` to the [`NEAR_NETWORKS` configuration](https://github.com/near/near-explorer/blob/master/frontend/next.config.js#L4-L15) [let @frol know if you need help with understanding that configuration setup])
- [x] The link to the lockup account should remain (obviously, only when the lockup account exists for the account)
- [x] The lockup balances should be removed (we have issues with keeping them up to date, so we decided to contentrate our efforts on Wallet Profile page)

**Comment by khorolets** [comment]
@frol could you update Acceptance Criteria as we've changed them on the fly?
