### ISSUE TITLE
Bug: Code Hash not matching near-api-js account.state().code_hash

### ISSUE THREAD

**Issue by mattlockyer** [near/near-explorer#465]
## Bug

From near-api-js
![image](https://user-images.githubusercontent.com/321340/97757196-822a1500-1ab9-11eb-8c6a-fbbab47c6657.png)

From explorer:
![image](https://user-images.githubusercontent.com/321340/97757212-8b1ae680-1ab9-11eb-88e6-a72616c1c2f3.png)

Contract is no-std super minimal replacement for multisig contract so user can withdraw storage bytes after disabling
```
#![no_std]
#![feature(core_intrinsics)]
#[panic_handler]
#[no_mangle]
pub fn on_panic(_info: &::core::panic::PanicInfo) -> ! {
    ::core::intrinsics::abort();
}
```

**Comment by frol** [comment]
If the value is different for you, it is a bug in near-api-js as Explorer value exactly matches the RPC output:

```json
$ curl https://rpc.testnet.near.org -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "method": "query", "params": {"request_type": "view_account", "account_id": "tl32.testnet", "finality": "final"}, "id": "dontcare"}' | jql '.'

{
  "jsonrpc": "2.0",
  "result": {
    "amount": "497974700724323488400000000",
    "locked": "0",
    "code_hash": "55E7imniT2uuYrECn17qJAk9fLcwQW4ftNSwmCJL5Di",
    "storage_usage": 356804,
    "storage_paid_at": 0,
    "block_height": 22190263,
    "block_hash": "12JenZBMdo5rxdzESmpGXKZBfYZJh6YijZ7WRme2LqgJ"
  },
  "id": "dontcare"
}
```

This matches the output I see on Explorer: https://explorer.testnet.near.org/accounts/tl32.testnet

**Comment by mattlockyer** [comment]
Yes sorry it was stale account state in wallet, just verified. Thanks @frol
