### ISSUE TITLE
Compute Circulating Supply and expose via backend

### ISSUE THREAD

**Issue by frol** [near/near-explorer#489]
*This is only applicable to mainnet*

*This issue is blocked on #478*

`Circulating Supply = Total Supply - Tokens locked in the Lockup contracts`

## Implementation Notes

Here is how to compute the value:

1. Total Supply is available though RPC `block` method (see `header->total_supply`)
2. Tokens locked in the lockup contracts needs to be queried individually:
2.1. Query Indexer for Explorer database for all the lockup accounts: `SELECT account_id FROM accounts WHERE account_id LIKE '%.lockup.near'`
2.2. Use [account-lookup code](https://github.com/near/account-lookup) to query the still locked balance
3. Sum up all the locked balances and subtract it from the Total Supply

NOTE: Make sure you pin a specific block height when you query the Total Supply and every individual contract state (through the account-lookup)

Compute the value every 2 hours on the backend and store the value in memory (if the computation takes too long, consider storing it in SQLite). Expose the precomputed value via WAMP `get-circulating-supply` method.

## Acceptance Criteria

- [x] The value is computed correctly (compare with the projection)
- [x] Non-mainnet networks return undefined
- [x] The value is re-computed every 2 hours (note: adjust the number if necessary)

**Comment by shelegdmitriy** [comment]
@telezhnaya is this issue still relevant?
