### ISSUE TITLE
Aggregate Deposit from Actions within Transactions

### ISSUE THREAD

**Issue by icerove** [near/near-explorer#521]
## Story

Please add query for total number of deposit from actions within daily total transactions. Includes:
1. transfers between accounts, 
2. deposits on contract calls and 
3. transfers from locked accounts as well

## Acceptance Criteria

- [x] use format we already have in backend
- [x] wamp have the exposed function to query the number
- [x] Tested

**Comment by frol** [comment]
@icerove Please, assign all bugs to me, so I can clarify the details and prioritize them properly.

How urgent is this? Who is the consumer?

I don't believe we have bandwidth to work on this item before we finish with Structured Errors for JSON RPC, which is at best will take us a few weeks to complete.

**Comment by icerove** [comment]
this is one part of network GDP I discussed with you and it is from Erik. It is not urgent since the concept could change in the future and need discuss. @frol @khorolets

**Comment by khorolets** [comment]
@frol it hasn't took me too long between Structured Errors for JSON RPC pull request reviews.
