### ISSUE TITLE
24 hour transaction volume is confusing

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#532]
<img width="747" alt="Screen Shot 2021-02-07 at 5 05 49 PM" src="https://user-images.githubusercontent.com/13601726/107165145-d79e7980-6966-11eb-8ee9-7eadfc69cc2d.png">

As shown here, it seems that the 24 hour volume is not the number of transactions in the past 24 hours, but rather the number of transaction since some fixed time every day. I don't think this is the best way to display transaction volume.

**Comment by frol** [comment]
Resolved with #536
