### ISSUE TITLE
Empty values are displayed on the Online Nodes page

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-explorer#540]
Go to https://explorer.near.org/nodes/online-nodes and observe an empty values (pay attention on "@"). It seems that in some cases `accountId` is empty and shown on the page as "@" and `status` is empty too. In some cases `accountId` is empty but `status` is available.

<img width="1085" alt="Снимок экрана 2021-02-11 в 19 00 38" src="https://user-images.githubusercontent.com/34593263/107671170-37b15a80-6c9c-11eb-92cb-18c97212dbb9.png">

**Comment by bowenwang1996** [comment]
This is because telemetry reports the account id it reads from the validator key file and if a node does not have such a file it will be empty. @frol maybe we should just hide `@` in this case or come up with some better design.

**Comment by frol** [comment]
Yeah, we should probably either use the node id (the hash that is on the right) or have a generic string there like "non-validating node"

**Comment by shelegdmitriy** [comment]
@frol , so what should I do: check accountId and if it's empty show string "non-validating node" or show "`@<nodeId>`" instead?

**Comment by frol** [comment]
Let me refactor it a bit on the backend side first and then I suggest we display "non-validating node" for every record that is not `is_validator`

**Comment by frol** [comment]
Not relevant anymore
