### ISSUE TITLE
Infinity loader on the page after re-navigation

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-explorer#541]
Go to https://explorer.near.org/ and click on the **Explore** dropdown menu. Navigate to **Accounts** page. After it open the **Explore** dropdown menu and navigate to **Accounts** page ones again. After this steps you'll see the infinite loader. 

Potentially related to #492 

This issue relates to **Accounts**, **Blocks** and **Transactions** pages.

**Comment by telezhnaya** [comment]
Not sure if it's the same or not:
Go to https://explorer.near.org/ and put any username to search field. Works fine.
Put another username to search field. Transactions for this user will load endlessly.

**Comment by frol** [comment]
I guess the root cause is the same. There is some race condition there.
