### ISSUE TITLE
Account Creation Issue

### ISSUE THREAD

**Issue by icerove** [near/near-explorer#551]
## Story

see this account: https://explorer.near.org/accounts/096985b8bb52a859d75c7b0e84889bb46fb9346524e264141f667c8954868184
with no action with create account, the create timestamp is not correct, it seems like update with transactions

## Acceptance Criteria

- [ ] account without create account is correct showing the create timestamp
- [ ] Mobile ok
- [ ] Tested

**Comment by frol** [comment]
Closing in favor of https://github.com/near/near-indexer-for-explorer/issues/68
