### ISSUE TITLE
Fix network icon colors in the network dropdown

### ISSUE THREAD

**Issue by frol** [near/near-explorer#564]
It is a follow-up issue (https://github.com/near/near-explorer/pull/507#pullrequestreview-583541665):

> The indicators in the network dropdown are all the same color, so unless you actually select one, the unique color associated with each ENV is not visible. Each network should be represented by its unique color at all times, including in the dropdown.

![image](https://user-images.githubusercontent.com/304265/109003308-0bc3ab00-7686-11eb-85a3-50b890f64eaf.png)

![image](https://user-images.githubusercontent.com/304265/109003357-1c742100-7686-11eb-9fa8-37449d73ef6b.png)

**Comment by ilyar** [comment]
https://github.com/near/near-explorer/pull/608
