### ISSUE TITLE
UI clash in stats

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-explorer#569]
Observe: https://explorer.near.org/stats

<img width="302" alt="Screen Shot 2021-03-01 at 5 10 29 PM" src="https://user-images.githubusercontent.com/175486/109581422-25fbef80-7ab1-11eb-94a9-fbbac4510e09.png">

**Comment by icerove** [comment]
We are going to delete that sidebar for now, but still need design for stats page. @corwinharrell

**Comment by frol** [comment]
Well, this issue is resolved. I am closing this in favor of #572
