### ISSUE TITLE
Do we miss negation in our message?

### ISSUE THREAD

**Issue by telezhnaya** [near/near-explorer#605]
https://github.com/near/near-explorer/blob/master/frontend/src/components/contracts/ContractDetails.tsx#L129

```
Locked contract means that there are no access keys allowing the
contract code to be re-deployed (e.g. even a single FullAccess
permission access key **(does not ?)** casts the locked status to "No").
```

**Comment by telezhnaya** [comment]
In the interface:
<img width="1147" alt="Screenshot 2021-04-15 at 10 13 16" src="https://user-images.githubusercontent.com/11246099/114829161-68645c00-9dd3-11eb-9bba-a7a00aa5d328.png">

**Comment by frol** [comment]
Nope, the message is fine. Locked contract is "immutable". If you have a full access key, the contract is not locked since you can re-deploy the contract code

**Comment by telezhnaya** [comment]
Got it, thank you!

I was thinking why I was confused with this message. Can we remove the word "even"?
