### ISSUE TITLE
[BUG] Gas Fee tab is missing on the Stats page

### ISSUE THREAD

**Issue by frol** [near/near-explorer#626]
Please, check why "Gas Fee" tab on the "GasUsedByDate" component is not displayed sometimes:

https://github.com/near/near-explorer/commit/559df0030115e6fc33cfb1b9c3116cc514377e16#diff-748199d40d15dce01dcd66263eb3cfe0075bda629b24e7ebd0821a80e0dcfb01R153

![image](https://user-images.githubusercontent.com/304265/118020259-43aac800-b330-11eb-8aeb-6874a6c55f30.png)

**Comment by icerove** [comment]
I see that on the local and I think it is because last time update this gas price is broken:
https://github.com/near/near-explorer/blob/254159a096a3c9398ce951ce877ce53692864beb/frontend/src/components/stats/GasUsedByDate.tsx#L25

and fee is also broken because of this

**Comment by frol** [comment]
@icerove Would you be able to submit a PR resolving the issue?

**Comment by frol** [comment]
Resolved in #659
