### ISSUE TITLE
Expose average fees in the last 24 hours and 7 days through API

### ISSUE THREAD

**Issue by frol** [near/near-explorer#627]
Expose two API endpoints for fees in 24h and in 7d for https://cryptofees.info/ requested a few times.

Reach out to https://cryptofees.info/submit-project and/or ping https://twitter.com/dmihal who runs that website

**Comment by shelegdmitriy** [comment]
@frol, does I need to create a new page for those metrics or I can add it to Stats page?

**Comment by frol** [comment]
@shelegdmitriy The SQL query is so slow that it never finishes its execution on mainnet.

The following query is fine and performs fast:

```sql
SELECT
   DATE_TRUNC('day', NOW() - INTERVAL '1 day') AS date,
   SUM(execution_outcomes.tokens_burnt) AS fee
FROM execution_outcomes
WHERE
   executed_in_block_timestamp >= (CAST(EXTRACT(EPOCH FROM DATE_TRUNC('day', NOW() - INTERVAL '1 day')) AS bigint) * 1000 * 1000 * 1000)
AND
    executed_in_block_timestamp < (CAST(EXTRACT(EPOCH FROM DATE_TRUNC('day', NOW())) AS bigint) * 1000 * 1000 * 1000);
```

Instead of aggregating the results on the database side, let's query the database once per day even though that is usually not recommended, but in this case, we are not going to make more than 7 requests and they seem to take less time, and don't get cancelled due to long execution time.

**Comment by shelegdmitriy** [comment]
@dmihal FYI we've just submitted google form with all the details
