### ISSUE TITLE
Accounts with a lot of transactions are slow to load

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#628]
It took ~1 minute to load the page when I searched for `near`. This is very suboptimal user experience.

**Comment by frol** [comment]
Same for `ref-finance.near`

**Comment by frol** [comment]
It seems that there are two types of queries that are too slow:

1. counting the number of transactions
2. fetching the list of transactions

I will get back with more details later

**Comment by frol** [comment]
Scaling the DB instance to have more resources and improving the query for transaction fetching in #633 the page opens in ~5 seconds. It is still suboptimal, but at least manageable. We need to improve the pagination and decouple fetching heavy data so they are pulled asynchronously
