### ISSUE TITLE
When function call arguments are empty, explorer is stuck on "Loading..."

### ISSUE THREAD

**Issue by mikroskeem** [near/near-explorer#631]
For example: https://explorer.testnet.near.org/transactions/BGWDmSzSJ6FEEVuKvWaXViPNbPiNn5V6jDV3EDP5mNkU (and few other recent calls on this dev account).

Trick is to construct a FunctionCallAction with empty args vec. I think explorer assumes that args is never empty, and near-api-js also sets args to `{}` (string) when args aren't supplied.

**Comment by frol** [comment]
@mikroskeem Thanks for reporting it! We will resolve it later this week
