### ISSUE TITLE
Consider moving fonts usage from edge components to _app.jsx

### ISSUE THREAD

**Issue by frol** [near/near-explorer#638]
We include fonts in some of the edge components (NodeRow, ValidatorRow) instead of including them on the application level. To align fonts usage across the project, we should move fonts imports into `_app.jsx`.

Along this way, we should decide which fonts we really need (currently we use Inter, Roboto Mono, and Source Code Pro)

**Comment by luixo** [comment]
https://github.com/near/near-explorer/commit/2981df4052f0b4a1a833cfd0583730013d057a95#diff-3b52f8f125a7193fda32720ab509959d79ccc5cbc1e9404fbd2d4bc41a15935c
