### ISSUE TITLE
[2021 UX Reevaluation] – Design Discovery / Exploration

### ISSUE THREAD

**Issue by heycorwin** [near/near-explorer#665]
This is a placeholder issue so that we can cross-reference components of #662\. The content will be updated to include a summary of the work for each component as it is completed.

**Comment by reefoh** [comment]
After our initial research of the current state of Explorer, we defined a few guiding principles for the first phase of explorations.

1. Know our users
2. Curate and expose vital data
3. Promote Personalization
4. Subtract for Simplicity
5. Invisible Design (System feedback)
6. Data = Narrative (Tie data together in a sentence that connects it and provides significance) 

**Current Landing**
![Current workflow](https://user-images.githubusercontent.com/81179096/122981861-3689eb80-d368-11eb-9504-e7a918670b6e.png)

**Proposed Landing**
![Revised workflow](https://user-images.githubusercontent.com/81179096/122981909-4275ad80-d368-11eb-8ea4-e7142f25b744.png)

**Search Feedback (New Users)**
![Hypothesis](https://user-images.githubusercontent.com/81179096/122982023-60dba900-d368-11eb-906e-8bde7dc235da.png)

**Search Behaviors**
![Hypothesis-3](https://user-images.githubusercontent.com/81179096/122982290-af894300-d368-11eb-8517-00c9d57563cc.png)
![Hypothesis-6](https://user-images.githubusercontent.com/81179096/122982312-b57f2400-d368-11eb-8a1c-5282f1139b0e.png)

**Current Transaction Landing**
![Current workflow-1](https://user-images.githubusercontent.com/81179096/122982392-cfb90200-d368-11eb-824b-cc5f5d273d6c.png)

**Proposed Transaction Landing**
![Revised workflow-1](https://user-images.githubusercontent.com/81179096/122982468-e7908600-d368-11eb-8ffc-0a76fb952ab3.png)
![Hypothesis-7](https://user-images.githubusercontent.com/81179096/122982534-fd05b000-d368-11eb-99e2-93a8c88dc202.png)


**Current Validator Landing**
![Current Node](https://user-images.githubusercontent.com/81179096/122982163-88327600-d368-11eb-9772-c1f8b52cd678.png)

**Proposed Validator Landing**

More to follow the following upcoming research efforts.

**Comment by corwinharrell** [comment]
A couple of questions:

> After our initial research of the current state of Explorer...

Is this research summarized anywhere or is this what is shown in the images above?

**Re: Guiding Principles:** How did you arrive at the guiding principles outlined above? Are these assumptions/ideas for how the explorer could evolve, and if so, what are they informed by?

- Promote Personalization: Has there been an expressed need for users to be able to personalize their experience?
- Subtract for Simplicity: To what extent? Would be great to know how users are consuming the data we display currently in order to determine if _they_ feel there is a need to simplify.
- Invisible Design (System feedback): This is a bit vague, can you articulate a few more details about what is meant by this?

**Comment by reefoh** [comment]
Is this research summarized anywhere or is this what is shown in the images above?
At the global level these are all assumptions we will validate through our user research efforts in the coming weeks.

> Re: Guiding Principles: How did you arrive at the guiding principles outlined above? Are these assumptions/ideas for how the explorer could evolve, and if so, what are they informed by?

These Principles are mostly informed by the initial competitive analysis of PoS explorers. The research efforts will aim to validate or challenge these ideas.

> Promote Personalization: Has there been an expressed need for users to be able to personalize their experience?
In my initial discussions with a few people internally/close to the project, the use case of "Returning Users" was something that needed exploration. There was a common interest in the idea mostly for Developers and Delegators.

> Subtract for Simplicity: To what extent? Would be great to know how users are consuming the data we display currently in order to determine if they feel there is a need to simplify.
The Subtraction principle is pointed at things like the transaction categories. For instance the smart contract execution label: Called method: 'add_block_header' in contract: 0.client.ropsten.testnet - We refine this to: "Block Header"

This might be dependent on if there is a manageable set of possible labels. In addition to this we'll find out whether the Developer finds this subtraction useful or not.

> Invisible Design (System feedback): This is a bit vague, can you articulate a few more details about what is meant by this?
This invisible intelligence is directed at the proposed search categorization and corresponding data per result in the auto-suggestion pattern. This also needs validation across all user segments. The purpose of this is to quickly get users to a transaction or account without the need of a results page.

**Comment by reefoh** [comment]
Our research efforts have helped us to refine or eliminate the principles we started with.

Our new principles:

Know our validators
Provide Delegators Tools
Encourage Decentralization
Better Data Hierarchy
~~Curate and expose vital data
Promote Personalization
Data = Narrative~~ 

We've explored a couple concepts that point back to our new focus.

Here are some highlights:

### Stake Simulator
![image](https://user-images.githubusercontent.com/81179096/125228660-3021cc00-e2a3-11eb-9531-20c8d3339e09.png)
![image](https://user-images.githubusercontent.com/81179096/125228670-331cbc80-e2a3-11eb-8389-7df63c24a903.png)

### Validator Notifications
![image](https://user-images.githubusercontent.com/81179096/125228700-42036f00-e2a3-11eb-8628-330d68c7f3e9.png)

### Validator Profiles
![image](https://user-images.githubusercontent.com/81179096/125229049-edacbf00-e2a3-11eb-9800-b654f5633b50.png)

### Better Ranking
![image](https://user-images.githubusercontent.com/81179096/125229167-29e01f80-e2a4-11eb-982c-8588a42326bf.png)
