### ISSUE TITLE
[2021 UX Reevaluation] – User Research

### ISSUE THREAD

**Issue by heycorwin** [near/near-explorer#668]
This is a placeholder issue so that we can cross-reference components of #662\. The content will be updated to include a summary of the work for each component as it is completed.

**Comment by reefoh** [comment]
### **Who:** 
We are putting together a people panel of new and returning users segmented by the needs and use cases of: **The Validator, The Delegator, and The Developer.**

### **Recruitment** 
We'll be building this panel from both our internal relationships and our lovely community.

### **Research Phases:** 
1. Discovery and foundational empathy mapping (interviews and insight into daily workflows outside of Near experiences)
2. Existing Workflow Definition (How users navigate current Explorer experience)
3. Problem Definition & Hypothesis 
4. UX Explorations & Prototyping
5. User Testing & Feedback
6. Development & Launch

**Process:** All design efforts are ongoing and iterative. 
**Transparency:** Insights to be synthesized and shared along the way.
Community: Outside of formal research efforts the Near Community will be able to contribute to this effort in various ways.

**Comment by reefoh** [comment]
Previous Validator Survey: https://docs.google.com/forms/d/1xarv54e-fFSuD2AQorAPx4086z3zyS5ZNGwcLr4QkeQ/edit#responses
