### ISSUE TITLE
i18n bug on Transactions list page

### ISSUE THREAD

**Issue by frol** [near/near-explorer#688]
Occasionally, "xx ago" timer gets Chineese translation:

![image](https://user-images.githubusercontent.com/304265/126027496-0f9a1adc-2b5d-48d2-9adb-6cf4d7a47053.png)

https://explorer.near.org/transactions

**Comment by think-in-universe** [comment]
@frol Frol, do you have any clue about how to reproduce this issue? I tried a few times but didn't find a way to reproduce it.

**Comment by bowenwang1996** [comment]
Observed this as well (US west coast). @think-in-universe maybe try using a vpn?

**Comment by frol** [comment]
I managed to reproduce it:

1. Open the dashboard (/)
2. Click on “View All” next to Blocks
3. 
![5644C3F9-2D0C-42C2-A195-968CD1EA4144](https://user-images.githubusercontent.com/304265/126062258-cad17f9f-5df2-4843-a16c-afae4a444c1c.png)

It is reproducible in any browser I have

**Comment by think-in-universe** [comment]
thanks @bowenwang1996 @frol 

I fixed it with #689
