### ISSUE TITLE
End-to-End Test in CI is quite flaky

### ISSUE THREAD

**Issue by think-in-universe** [near/near-explorer#690]
### Description

The end-to-end test in CI is really flaky. It failed 60~70% of all the times we submitted PRs even if the changeset shouldn't break the test. 

Can we extend the timeout in cypress test caes from 5s to 10s maybe?

Or is it caused by slow performance of some pages which we also need to fix?

**Comment by frol** [comment]
This should be fixed with https://github.com/near/near-indexer-for-explorer/pull/139

I will re-open the issue if I see that CI fails again.
