### ISSUE TITLE
Explorer stats do not include data from last week

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#693]
It appears that https://explorer.near.org/stats stops at July 20th for some reason.

**Comment by frol** [comment]
Good catch! We might have messed up with rounding up down to a week boundary instead of a day boundary

**Comment by frol** [comment]
I restarted the Explorer backend and that resolved the issue, but I feel it got stuck on July 25th now. It seems the background job gets locked somewhere. I will investigate it further later this week.

**Comment by frol** [comment]
Restart resolved the bug, we will need to double-check what stuck/broke, but meanwhile the solution is to restart the backend.
