### ISSUE TITLE
Validators uptime is broken for some nodes

### ISSUE THREAD

**Issue by frol** [near/near-explorer#696]
## Problem

![image](https://user-images.githubusercontent.com/304265/128145181-488add58-aa6c-40ce-b27c-f6ee6aa5a82a.png)

## How did we discover this problem?

https://explorer.near.org/nodes/validators

Expand details about `dragonfly.poolv1.near`.

## What are we planning to do about it?

Let's fix it.

**Comment by shelegdmitriy** [comment]
It seems it's not relevant. @frol
