### ISSUE TITLE
Daily number of new accounts is broken

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#704]
On https://explorer.near.org/stats, the daily number of new accounts section is completely broken.
<img width="1212" alt="Screen Shot 2021-08-12 at 4 53 33 PM" src="https://user-images.githubusercontent.com/13601726/129284270-a6ae678b-ce82-4c1e-985f-a2205d21e4dd.png">

**Comment by frol** [comment]
The database queries for the stats page frequently times out. There is nothing we can do on the Explorer side today; we are blocked on https://github.com/near/near-indexer-for-explorer/issues/137
