### ISSUE TITLE
Explorer/Website: MalwareBytes Blocks Access Because a 3rd Party Site/Library is Flagged as a Phishing Site

### ISSUE THREAD

**Issue by gaia** [near/near-explorer#708]
![image](https://user-images.githubusercontent.com/87547/130006690-da9fc385-8403-43c9-9ed0-ebe765407dec.png)

just FYI (I know how to get around this), MBAM (likely the #1 anti malware software for windows) is giving this when I try to visit https://explorer.near.org.

The perceived threat comes from a site/library called out the main site

**Comment by frol** [comment]
@gaia Thanks for the heads-up! I have not seen this, and I have no experience with this MalwareBytes, but we will take a look into it

**Comment by frol** [comment]
@shelegdmitriy Can you see if there are online databases where Explorer is listed as a phishing site and how to get out of those lists?

**Comment by frol** [comment]
@gaia The data on your screenshot looks absolutely right to me. I don't use MalwareBytes, but I checkout our urls:

* https://explorer.near.org
* https://near-explorer-frontend.onrender.com (this is an internal URL, so nobody should really use it)

with the following tools:

* https://www.virustotal.com/gui/home/url
* https://sitecheck.sucuri.net/
* https://transparencyreport.google.com/safe-browsing/search
* https://www.urlvoid.com/

Everything is green. Can you double-check if that was just a glitch or it is still reproducible for you? (Please, send us more details about your OS and browser)

**Comment by gaia** [comment]
The internal FQDN got called out by the browser. I didn't type it in directly. As it should, MBAM screens all the FQDNs and compares against its own database. Keep in mind that MBAM is the reference client for Anti Malware, not Anti Virus (I use it in conjunction with the AV).

The free version of MBAM should have flagged it the same way my (paid) version does. But I just went to check it again and either MBAM decided that onrender.com was a false positive or the onrender.com ppl fixed their issue. The Explorer opens fine now, so I will close. Thanks guys.
