### ISSUE TITLE
Add missing translation to Chinese on Nodes page

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-explorer#710]
## Story

As a USER who views https://explorer.near.org/nodes/validators in Chinese, I want to see all terms in my native language so I can better understand what the metrics is and what is going on in a Near blockchain.

## Acceptance Criteria

- [ ] [Location](https://github.com/near/near-explorer/blob/master/frontend/src/translations/zh-hans.global.json#L104)

### Translate validator types:

- [ ] [joining](https://github.com/near/near-explorer/blob/master/frontend/src/translations/zh-hans.global.json#L121);
- [ ] [proposal](https://github.com/near/near-explorer/blob/master/frontend/src/translations/zh-hans.global.json#L129);
- [ ] [Idle](https://github.com/near/near-explorer/blob/master/frontend/src/translations/zh-hans.global.json#L132-L135);
- [ ] [newcomer](https://github.com/near/near-explorer/blob/master/frontend/src/translations/zh-hans.global.json#L136-L139);
- [ ] [on_hold](https://github.com/near/near-explorer/blob/master/frontend/src/translations/zh-hans.global.json#L140-L143);

### Translate metadata information about validator:

- [ ] [ValidatorMetadataRow](https://github.com/near/near-explorer/blob/master/frontend/src/translations/zh-hans.global.json#L168-L180)

**Comment by shelegdmitriy** [comment]
@think-in-universe @IsQiao Hey guys! Could you please help with this stuff?

**Comment by IsQiao** [comment]
Ok, I'll finish it.

**Comment by think-in-universe** [comment]
cool. thanks @IsQiao

**Comment by IsQiao** [comment]
Resolved in #670
