### ISSUE TITLE
Non-existent accounts inaccurately represented on Account Details page

### ISSUE THREAD

**Issue by frol** [near/near-explorer#715]
## Story

As a regular user who looks up an account that does not exist, I want to clearly see that it does not exist.

> This tx shows an account was created - https://explorer.testnet.near.org/transactions/3jXXadLvxRzAVgzaRE6gfP7fyCFnTbwM9RuzLfGuFA6f store-v45.a400.testnet
> This link shows the account - https://explorer.testnet.near.org/accounts/store-v45.a400.testnet
> However when i search the account on explorer, it can't be found 

https://t.me/neardev/12640

The problem is that `store-v45.a400.testnet` was not created since the receipt execution failed. Explorer did a poor job communicating it.

![image](https://user-images.githubusercontent.com/304265/130440776-8581ff9f-f2de-4636-b2d5-923b0cb6be35.png)

The account in question has been created since the discussion, so I created my own test case: `does-not-exist.frol4.testnet` does not exist on chain, and you cannot find it through search, but the Account Details page still partially displays some data: https://explorer.testnet.near.org/accounts/does-not-exist.frol4.testnet

## Acceptance Criteria

* [x] Account Details page should be consistent with the search (I suggest we report that the account does not exist if user navigates to the page directly; use `isAccountIndexed` to check if an account exists before fetching any other data)

**Comment by shelegdmitriy** [comment]
We resolved this issue a long time ago
