### ISSUE TITLE
Unable to build explorer backend inside Docker

### ISSUE THREAD

**Issue by telezhnaya** [near/near-explorer#719]
Backend uses 12 version of JS
It does not support `??` operator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
@shelegdmitriy used it recently in `backend/src/index.js`

I tried to bump up JS version: it's not so easy, it requires installing python and gives other weird issues.

We can easily change `??` to `||`, looks like it should work in our case.

@frol @khorolets

**Comment by frol** [comment]
I wonder how that works on production then :rofl:

**Comment by frol** [comment]
@telezhnaya try #722
