### ISSUE TITLE
Some charts on the stats page do not load

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-explorer#726]
Examples:
<img width="1157" alt="Screen Shot 2021-08-29 at 8 45 24 AM" src="https://user-images.githubusercontent.com/13601726/131256600-44ec64ab-893a-4044-a192-dd96964cce74.png">
<img width="1278" alt="Screen Shot 2021-08-29 at 8 45 37 AM" src="https://user-images.githubusercontent.com/13601726/131256602-363510d7-a686-4135-8c6c-45f13b1efde6.png">

**Comment by shelegdmitriy** [comment]
@frol I believe we solved this issue by moving to near-analytics. After that we haven't any issues with charts
