### ISSUE TITLE
Date Time Format for Chinese Language is Incorrect

### ISSUE THREAD

**Issue by think-in-universe** [near/near-explorer#727]
### Description

The date time format of account and transaction creation time is incorrect. e.g.: https://explorer.mainnet.near.org/transactions/9UfBN7A4QgGmfqjBB1PpFaer9BW2uXgNXto6dMpaE5DM

![image](https://user-images.githubusercontent.com/46699230/131889261-ea9521c2-5d43-44ab-b35d-c7f096f6b511.png)

The expected format should be "**9月2日, 2021, 下午9:39:16**"

**Comment by luixo** [comment]
Fixed
