### ISSUE TITLE
BUG: changing `WAMP_NEAR_EXPLORER_URL` variable for `frontend` in `docker-compose` doesn't do anything

### ISSUE THREAD

**Issue by mieubrisse** [near/near-explorer#733]
It seems that the CMD given to the `frontend` server, `["npm", "run", "start:local-wamp-with-indexer-testnet"]`, causes it to run a bunch of hardcoded stuff (and thus, ignore the `WAMP_NEAR_EXPLORER_URL` environment variable that Docker Compose sets). This just happens to work because the hardcoded `localhost:8080` is the same as what the WAMP server gets set to in the Compose file, but trying to run the WAMP on a different interface or port will cause the frontend to try in vain to connect to it on localhost:8080.

This can be seen clearly from what the `frontend` is doing in its logs:
```
> near-explorer@0.0.1 start:local-wamp-with-indexer-testnet

> env 'NEAR_NETWORKS=[{"name": "testnet", "explorerLink": "http://localhost:3000/", "aliases": ["localhost:3000", "127.0.0.1:3000"], "nearWalletProfilePrefix": "https://wallet.testnet.near.org/profile"}]' npm run start:local-wamp-with-indexer

> near-explorer@0.0.1 start:local-wamp-with-indexer

> env NEAR_EXPLORER_DATA_SOURCE=INDEXER_BACKEND npm run start:local-wamp

> near-explorer@0.0.1 start:local-wamp

> env WAMP_NEAR_EXPLORER_URL=ws://localhost:8080/ws npm run start

> near-explorer@0.0.1 start

> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

EDIT: More specifically, this happens because of this task in `frontend`'s `package.json`: `"start:local-wamp": "env WAMP_NEAR_EXPLORER_URL=ws://localhost:8080/ws npm run start"`

**Comment by frol** [comment]
@mieubrisse Thanks for bringing this up! I will take a closer look shortly

**Comment by frol** [comment]
@mieubrisse Yeah, this is indeed a bug just as you described. Would you mind submitting a PR fixing it? :pray:

**Comment by mieubrisse** [comment]
@frol happy to do so but what should be the fix? I could remove the `WAMP_NEAR_EXPLORER_URL` from the `package.json`, but from the way it's structured it looks like devs might rely on the current configuration

**Comment by frol** [comment]
@mieubrisse I think we should change `docker-compose.yml` to use pure `npm run start` and specify all the environment variables explicitly in the `docker-compose.yml`, so they are fully configurable.

**Comment by luixo** [comment]
We moved away from WAMP, problem is solved :)
