### ISSUE TITLE
Circulating and total supply is 1000 times more than it should be

### ISSUE THREAD

**Issue by telezhnaya** [near/near-explorer#750]
https://explorer.near.org/stats

Total supply at the beginning was 1000M
But on the chart, it's 1000 000 M (1 000 000 000 000)

Checked the data in the DB, it's fine. So it should be an error on Explorer side.

BTW, it anyway has too many zeros, let's show it in millions
@shelegdmitriy @frol what do you think?

Found another issue: we should not show this chart on Testnet, please remove it there

**Comment by shelegdmitriy** [comment]
@telezhnaya Yeah, agree. But what should we do with chart on testnet? Just hide or display placeholder with explaining (that we don't calculate circulating supply for testnet or something like that)? @frol WDYT?

**Comment by telezhnaya** [comment]
I think it's better just to hide it

Circulating supply makes no sense when tokens have no real price

**Comment by telezhnaya** [comment]
Reopen because we still want to show values in millions

**Comment by shelegdmitriy** [comment]
I've created a new issue for rest of improvements #752
