### ISSUE TITLE
Optimize the computation of total transaction count for each account

### ISSUE THREAD

**Issue by telezhnaya** [near/near-explorer#773]
We can reuse https://github.com/near/near-analytics to collect ingoing and outgoing transactions for each user faster.

Current solution: 
https://github.com/near/near-explorer/blob/master/frontend/src/libraries/explorer-wamp/accounts.ts#L87-L102
BTW, don't we want to move sql statement to backend? That was non-trivial to find this place.
Current solution takes ~250s for heavy account id (I took 'near').
Our plan is to combine the data from Analytics DB (for historical data) and from Indexer DB (for today's rows).

## Outgoing transactions
We have outgoing transactions collected in [Analytics](https://github.com/near/near-analytics). We can query for it, it will give us the number for all the period except the last day.
Then, we should query for transactions count for the last day (using Indexer DB) and sum up the numbers. 
It takes 2s + 2s.

## Ingoing transactions
It's a bit harder for ingoing transactions: we should join with `receipts` table there. We can't just copy-paste SQL from current solution and add `where timestamp > start_of_today`, it will still take 70s, unacceptable.

After massive playing with this query, I came up with:
```
SELECT COUNT(DISTINCT transactions.transaction_hash)
FROM transactions
LEFT JOIN receipts ON receipts.originated_from_transaction_hash = transactions.transaction_hash
    AND transactions.block_timestamp > start_of_today
WHERE receipts.included_in_block_timestamp > start_of_today
    AND transactions.signer_account_id != requested_account_id
    AND receipts.receiver_account_id = requested_account_id
``` 
This one works 1s, cool.

On the Analytics side, the query should look smth like that
```
SELECT receipts.receiver_account_id, COUNT(DISTINCT transactions.transaction_hash)
FROM transactions
LEFT JOIN receipts ON receipts.originated_from_transaction_hash = transactions.transaction_hash
    AND transactions.block_timestamp >= start_of_day1
    AND transactions.block_timestamp < start_of_day2
WHERE receipts.included_in_block_timestamp >= start_of_day1
    AND receipts.included_in_block_timestamp < (start_of_day2 + 10 minutes)
    AND transactions.signer_account_id != receipts.receiver_account_id 
GROUP BY receipts.receiver_account_id
```
It's important to add 10 minutes (the constant is configurable) to receipt border, we should pack the transaction with all their receipts together, or the numbers will not be accurate. Other receipts from the next day will be naturally ignored.
It takes 2s.

So, if we rely on multitheading, we have 2 seconds per account. Or, 7 seconds total. Even 7 seconds sounds good enough.

**Comment by telezhnaya** [comment]
@frol I want your opinion here 🙂

**Comment by frol** [comment]
Thanks for the detailed plan, it all sounds good to me :+1: 

@telezhnaya I asked @shelegdmitriy to pick it up from you and work on the implementation side of it.

> BTW, don't we want to move sql statement to backend? That was non-trivial to find this place.

#774

**Comment by telezhnaya** [comment]
@frol is it true that @shelegdmitriy is also ready to make the PR to analytics tool? 😇

**Comment by frol** [comment]
@telezhnaya Well, that might be too much for him, but you may give it a try (just keep in mind that not everyone knows Python and its tooling [env, and other concepts])
