### ISSUE TITLE
Upgrade `Next.js` and `Jest` to latest versions

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-explorer#796]
## Acceptance Criteria

- [ ] Upgrade `Next.js`;
- [ ] Upgrade `Jest`;
- [ ] Update unit tests;
- [ ] Tested

## Assets

- Mockup: 

## NOTES

- Since the release of Next.js 12, Next.js now has built-in configuration for Jest. So it would be great to implement it as well https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler;
- Sometimes unit tests fails without any reason. That's why we need to reorganize all unit tests to avoid failing

**Comment by luixo** [comment]
`Next.js` upgrade is now [addressed](https://github.com/near/near-explorer/pull/809)

**Comment by luixo** [comment]
`Jest` upgrade is now [addressed](https://github.com/near/near-explorer/pull/810)

**Comment by luixo** [comment]
I'm not sure what was meant by "update unit tests", but I added [proper CSS snapshotting](https://github.com/near/near-explorer/pull/814) and would rather link it to this issue.
