### ISSUE TITLE
Seat price after switching to the new validator seat allocation algorithm

### ISSUE THREAD

**Issue by nikurt** [near/near-explorer#797]
Protocol version 49 will introduce the new validator seat allocation algorithm, which will change the way the seat price is calculated.
Please consider updating the "Seat Price" field on the Nodes pages.

Details on how to calculate Seat Price can be found here: https://github.com/near/near-cli/issues/895

**Comment by frol** [comment]
Just for the reference, the view seat allocation algorithm support in near-cli is blocked on https://github.com/near/near-api-js/issues/744

**Comment by frol** [comment]
@shelegdmitriy Please, accommodate the new near-api-js version and update the `findSeatPrice` usage accordingly. near-cli-js has already updated it: https://github.com/near/near-cli/pull/897
