### ISSUE TITLE
Wildcard module declaration

### ISSUE THREAD

**Issue by luixo** [near/near-explorer#802]
## Story

As a newcomer to this repository, I'm pretty confused with [declaration](https://github.com/near/near-explorer/blob/master/frontend/additional.d.ts#L12) `declare module "*"` in typescript extraneous declaration [file](https://github.com/near/near-explorer/blob/master/frontend/additional.d.ts).
It seems like a smelly code for me, combining with [no monorepo tooling](https://github.com/near/near-explorer/issues/803) it caused an irritating bug of every module being linked to this declaration, effectively ruining all type checks.

Seems like this line was [added](https://github.com/near/near-explorer/commit/880990d72bb48eefd60786a27fee53f27145b39d) to help out with absent type on `datamaps` module, but probably it was an overkill to add a wildcard for that.

## Proposals

- Replace wildcard module definition to `datamaps` module definition
- Either update `datamaps` to 0.5.9 which has type definitions and write own react components or make a PR with types to `react-datamaps` package (propose your own solution!)
- Be more strict on wildcards in general :)

**Comment by frol** [comment]
Given that the GeoMap Page is now dead, we may as well just remove datamaps for now.

Well, there were some historical reasons why I went stupid and merged the PR before we addressed all the code quality issues. We should definitely improve it.

@luixo If this breaks your productivity, I suggest you address this issue first.

**Comment by luixo** [comment]
> Given that the GeoMap Page is now dead, we may as well just remove datamaps for now.

Should we remove it completely? You can still access it via direct link.

**Comment by frol** [comment]
Yes, go ahead and remove it completely
