### ISSUE TITLE
A bunch of warnings on test run

### ISSUE THREAD

**Issue by luixo** [near/near-explorer#810]
## Story

When running tests (via jest) one stumble upon a bunch of similar warning messages like this:
```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Warning: An update to Link inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Link (/Users/luixo/git/near/near-explorer/frontend/node_modules/next/client/link.tsx:131:19)
```

Is there a reason renders are not wrapped in `act` as react docs suggest?

## Acceptance Criteria

- [ ] No warning emitted on test run

**Comment by frol** [comment]
It was ugly, but it worked, and we never had time to address it.

> Is there a reason renders are not wrapped in act as react docs suggest?

I did not see that suggestion, I believe it was a less helpful message. Feel free to address it.
