### ISSUE TITLE
Data about validators is out-of-date

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-explorer#821]
## Story

Here is a report from discord from one of validators on testnet
>_My node has been validating and the explorer shows outdated info here:_
![unknown](https://user-images.githubusercontent.com/34593263/146199999-9cdf35d0-4184-40fe-952e-bc1a0408f81b.png)
>The issues are: 1. I am validating right now, not in the proposals. 2. telemetry outdated. 3. node is now in release 1.23.0

## Acceptance Criteria

- [x] #826 
- [x] #830

**Comment by shelegdmitriy** [comment]
We have a lot of duplicated in our telemetry database. The thing is we store the data by `node_id` (as primary key) but validators can change their `node_id` and then we select from database only first record and display on the page. I have found it in db for testnet, but I believe these can be on mainnet too (coudn't connect to mainnet db to check it).
@frol @telezhnaya I would like to hear your opinions here

**Comment by telezhnaya** [comment]
Do you have an idea what primary key should work here?

**Comment by shelegdmitriy** [comment]
Here is our query: 
```
SELECT ip_address, account_id, node_id,
       last_seen, last_height, status,
       agent_name, agent_version, agent_build,
       latitude, longitude, city
FROM nodes
WHERE account_id IN (:accountArray)
```
> Do you have an idea what primary key should work here?

No, instead I was thinking about selecting las record of `account_id` from database by `last_seen`. So even some validator has more then 1 record we always choose the last one. But this is like temporary solution and I'm not sure is it a good idea

**Comment by shelegdmitriy** [comment]
We fixed only one part of this issue
