### ISSUE TITLE
Explorer Stats: Total Stake Volume for Epoch chart showing as 0

### ISSUE THREAD

**Issue by tonykau1** [near/near-explorer#850]
On https://explorer.near.org/stats the Total Stake Volume shows as "0" and the last chart - "Stake Volume for Validating Nodes" is showing only the list of nodes, but 0 for each node's volume.

**Comment by frol** [comment]
@shelegdmitriy  Given that that chart duplicates the information available on the nodes page, let's remove it from the stats page.
