### ISSUE TITLE
Explorer indexer far behind current block

### ISSUE THREAD

**Issue by danielwpz** [near/near-explorer#855]
hey, seems the explorer is not currently showing recent blocks/transactions for two days. we almost have doubled the amount of transactions these days and a lot of users are complaining about this, they are afraid of losing assets.

If we can please try fix it asap, many thanks!

**Comment by luixo** [comment]
This issue is [addressed](https://github.com/near/near-indexer-for-explorer/issues/226) in indexer-for-explorer repo.

**Comment by frol** [comment]
@danielwpz Sorry for the inconvenience! Explorer is back to normal.

**Comment by danielwpz** [comment]
cool!
