### ISSUE TITLE
The datetime not rendered in user's language

### ISSUE THREAD

**Issue by think-in-universe** [near/near-explorer#871]
With the recent i18n code refactor, it seems now in pages like Account and Transaction, etc., the default language for date is Russian when rendering the page returned by SSR.

To reproduce, try open the page in browser: https://explorer.near.org/accounts/alice.near   

![image](https://user-images.githubusercontent.com/46699230/150925588-9364b8fc-e2ba-4f5d-8785-73b2f53a42dd.png)

The date is in Russian, even if I switch the language to Chinese.

![image](https://user-images.githubusercontent.com/46699230/150925885-452b8b7d-bf43-49b2-a0b7-daa9172cc3c8.png)

To fix this, in SSR, we should render the date in the selected language.

**Comment by luixo** [comment]
Thanks for the catch!
Issue is address here: https://github.com/near/near-explorer/pull/872
