### ISSUE TITLE
near account does not say that there is actually a contract deployed to it

### ISSUE THREAD

**Issue by frol** [near/near-explorer#878]
https://explorer.near.org/accounts/near

There should be a contract section on that page, but it is missing.

![image](https://user-images.githubusercontent.com/304265/151952503-4553b2b6-0b37-4ea2-8cc7-f464a1eeca90.png)

Notice that there is contract code hash

**Comment by shelegdmitriy** [comment]
We use this query to extract information about contract (https://github.com/near/near-explorer/blob/master/backend/src/db-utils.js#L1113-L1128):
```
SELECT
        DIV(receipts.included_in_block_timestamp, 1000*1000) AS block_timestamp,
        receipts.originated_from_transaction_hash AS hash
       FROM action_receipt_actions
       LEFT JOIN receipts ON receipts.receipt_id = action_receipt_actions.receipt_id
       WHERE action_receipt_actions.action_kind = 'DEPLOY_CONTRACT' AND action_receipt_actions.receipt_receiver_account_id = :account_id
       ORDER BY action_receipt_actions.receipt_included_in_block_timestamp DESC
       LIMIT 1
```

but this query fails 
<img width="642" alt="Снимок экрана 2022-02-01 в 15 29 53" src="https://user-images.githubusercontent.com/34593263/151977258-ae101f29-3f04-44bd-b893-b6d000e3dc6f.png">

I tried to run this query in DBeaver but it fails after 57s

**Comment by luixo** [comment]
@telezhnaya 
It seems like DB takes too much to query actions on account with a huge amount of them, and `near` is one of those.

**Comment by shelegdmitriy** [comment]
That's right. But how we can fix this?

**Comment by telezhnaya** [comment]
I've created the scratch of the solution to make the query faster.
Be careful, the Analytics DB is updated only at midnight.

It means that you still need to make the query to the indexer, but with an additional clause:
```
WHERE timestamp >= today_midnight
```
Good news: the query should work really fast with this clause.

So, it should be a combination of 2 fast queries. We've implemented similar logic with @shelegdmitriy before

**Comment by shelegdmitriy** [comment]
@telezhnaya Thanks! I'll prepare PR after yours

**Comment by telezhnaya** [comment]
I suggest you make no movements until I merge this PR :) 
The interfaces could change during the review.
I will ping you separately

**Comment by telezhnaya** [comment]
@shelegdmitriy I deployed it.
You can have a look.


I suggest you to run 3 queries.
The first one to Analytics DB to find the latest historical option
```
SELECT * FROM deployed_contracts
WHERE deployed_to_account_id = 'near' -- put here the desired account_id
ORDER BY deployed_at_block_timestamp DESC
LIMIT 1
```
The second one to Analytics DB to find the latest update in general and save the timestamp
```
SELECT deployed_at_block_timestamp FROM deployed_contracts
ORDER BY deployed_at_block_timestamp DESC
LIMIT 1;
```
The third one to Indexer DB to find the fresh update. 
```
SELECT
        DIV(receipts.included_in_block_timestamp, 1000*1000) AS block_timestamp,
        receipts.originated_from_transaction_hash AS hash
       FROM action_receipt_actions
       LEFT JOIN receipts ON receipts.receipt_id = action_receipt_actions.receipt_id
       WHERE action_receipt_actions.action_kind = 'DEPLOY_CONTRACT' 
       AND action_receipt_actions.receipt_receiver_account_id = 'near' -- desired account id
       AND action_receipt_actions.receipt_included_in_block_timestamp > 1643759569060429373 -- timestamp from p.2
       ORDER BY action_receipt_actions.receipt_included_in_block_timestamp DESC
       LIMIT 1;
```
Then combine 1 and 3 to get the result

**Comment by shelegdmitriy** [comment]
@telezhnaya Wow! Thank you for such detailed description 🙂
