### ISSUE TITLE
Explorer frontend often crashes in production

### ISSUE THREAD

**Issue by frol** [near/near-explorer#884]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/304265/152184892-36fe4c36-0f3f-4781-a6bd-69b45eb50f3a.png">

I often see Explorer frontend is not reachable after the recent release of #841 

It crashes roughly every hour.

**Comment by luixo** [comment]
It took me way more than one could expect to find the issue (we should implement more logging / monitoring / alerting though it wouldn't be sufficient in this case).
The root issue is the one in `bn.js` library: https://github.com/indutny/bn.js/issues/186
Fix will happen in: https://github.com/near/near-explorer/pull/899
