### ISSUE TITLE
Create the account summary view for the new account details page - prototype

### ISSUE THREAD

**Issue by AustinBaggio** [near/near-explorer#895]
## Story

As a developer interacting with the near blockchain, I want to view an account's summary on the explorer, so that I can know its key information at a glance

## Acceptance Criteria

Display Account Summary Details

*   [ ] Account address
*   [ ] Created by (Link to transaction when clicked)
*   [ ] Storage used
*   [ ] Account Type (User, Application)
*   [ ] Balance (Display available balance here - sum of native liquid balance and native staked balance)
*   [ ] Number of transactions

Micro-interactions:

*   [ ] Copy address hover link
*   [ ] Link to account on wallet w icon

Req:

*   [ ] Manually tested by @reefoh

## Assets

*   [Mockup (figma - "Prototype Production Page")](https://www.figma.com/file/Ggv0tYCcGwGnTH1vRUJb9S/Explorer-Redesign?node-id=1044%3A5281)

**Comment by AustinBaggio** [comment]
Updated Figma to the _[prototype production](https://www.figma.com/file/Ggv0tYCcGwGnTH1vRUJb9S/Explorer-Redesign?node-id=1044%3A5281)_ page

**Comment by luixo** [comment]
I think we might close that for now, as we released a beta activity page: https://explorer.near.org/beta/accounts/near
