### ISSUE TITLE
Transaction count incorrect when viewing wrap.near

### ISSUE THREAD

**Issue by AustinBaggio** [near/near-explorer#905]
![image](https://user-images.githubusercontent.com/10964366/154759903-d98ee240-db57-4ffa-a59c-19c3f41dd311.png)

Looking at the account activity, there are obviously way more than 8 transactions. 
https://explorer.near.org/accounts/wrap.near

**Comment by frol** [comment]
That is totally odd!

@shelegdmitriy Can you take a look? And reach out to Olga is necessary

**Comment by shelegdmitriy** [comment]
@AustinBaggio thanks for catching! I've prepared a PR with fix. That was a small mistake in code after huge refactoring
