### ISSUE TITLE
Guildnet explorer down

### ISSUE THREAD

**Issue by DDeAlmeida** [near/near-explorer#922]
Hi all, we have currently issue on https://explorer.guildnet.near.org/nodes/validators

Keep loading

Indexer Is updated to the latest version
Contract helper too

**Comment by luixo** [comment]
I restarted the guildnet backend, it works now. Backend issues will be addressed soon.

**Comment by DDeAlmeida** [comment]
@luixo Issue is back...

**Comment by DDeAlmeida** [comment]
@luixo Something strange.
Explorer looks ok but Nodes online => 0
and Telemetry is wrong

Maybe need a restart ^^
Thank you :)
