### ISSUE TITLE
Guildnet explorer down

### ISSUE THREAD

**Issue by DDeAlmeida** [near/near-explorer#973]
Hi all, we have currently issue on https://explorer.guildnet.near.org/nodes/validators

Keep loading

Indexer Is updated to the latest version
Contract helper too

Same as https://github.com/near/near-explorer/issues/922

**Comment by luixo** [comment]
Loaded in a bit for me. Do you still have issues?

**Comment by DDeAlmeida** [comment]
> Loaded in a bit for me. Do you still have issues?

Yes. Look Node Active -> 0 but 65 node validating ??

**Comment by luixo** [comment]
It is fixed now (telemetry was not recieved because we lacked WRITE_DATABASE environment variables for guildnet on production).
